const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');
function host(){const ctx={RGBColor:function(){this.typename='RGBColor';},SpotColor:function(){this.typename='SpotColor';},ColorModel:{PROCESS:'process'},ImageColorSpace:{CMYK:'CMYK',RGB:'RGB'},ColorConvertPurpose:{defaultpurpose:0},app:{convertSampleColor(){return [0,0,0];}}};vm.createContext(ctx);for(const f of ['color/convert.js','color/deltaE2000.js','illustrator/selection.js','illustrator/swatches.js','illustrator/labels.js'])vm.runInContext(fs.readFileSync(path.join(root,'src',f),'utf8'),ctx);return ctx;}
const rgb=(r,g,b)=>({typename:'RGBColor',red:r,green:g,blue:b}),p=(c)=>({typename:'PathItem',filled:true,fillColor:c});
test('selection handles groups, compound paths, text and unsupported fills',()=>{const h=host(),red=rgb(255,0,0),blue=rgb(0,0,255),char={characterAttributes:{fillColor:blue}},doc={selection:[{typename:'GroupItem',pageItems:[p(red),{typename:'CompoundPathItem',pathItems:[p(red),p(red)]},{typename:'TextFrame',textRange:{characters:[char]}},p({typename:'GradientColor'})]}]};const a=h.ThreadMatch.collectSelection(doc);assert.equal(a.groups.length,2);assert.equal(a.groups[0].targets.length,2);assert.equal(a.skipped,1);assert.throws(()=>h.ThreadMatch.collectSelection({selection:[]}));assert.throws(()=>h.ThreadMatch.collectSelection({selection:[p({typename:'NoColor'})]}));});
test('global process swatches remain analyzable; gray and CMYK branches',()=>{const h=host(),T=h.ThreadMatch;assert.equal(T.illustratorColorToRGB({typename:'GrayColor',gray:100}).r,254.99999999999997);assert.equal(T.illustratorColorToRGB({typename:'CMYKColor',cyan:0,magenta:0,yellow:0,black:100}).r,0);const c={typename:'SpotColor',spot:{colorType:'process',color:rgb(50,60,70)},tint:100};assert.equal(T.collectSelection({selection:[p(c)]}).groups.length,1);assert.throws(()=>T.illustratorColorToRGB({typename:'SpotColor',spot:{colorType:'spot'}}));});
function document(){const doc={swatches:[],spots:[],textFrames:{add(){const f={textRange:{characterAttributes:{}},remove(){this.removed=true;}};return f;}}};doc.spots.add=function(){const spot={remove(){this.removed=true;}};Object.defineProperty(spot,'name',{set(v){this._name=v;doc.swatches.push({name:v,color:{typename:'SpotColor',spot:this,tint:100}});},get(){return this._name;}});this.push(spot);return spot;};return doc;}
const thread={code:'5924',name:'lemon',rgb:{r:200,g:180,b:0}};
test('apply creates one global process swatch and reuses it',()=>{const h=host(),T=h.ThreadMatch,d=document(),obj=p(rgb(22,33,44)),bucket={targets:[{kind:'path',item:obj}]};T.applyThread(d,bucket,thread);T.applyThread(d,bucket,thread);assert.equal(d.spots.length,1);assert.equal(obj.fillColor.spot.colorType,'process');assert.equal(d.swatches[0].name,'5924 · lemon');});
test('conflicting swatch is not overwritten',()=>{const T=host().ThreadMatch,d=document();d.swatches.push({name:'5924 · lemon',color:rgb(1,2,3)});assert.throws(()=>T.getThreadSwatch(d,thread));assert.equal(d.spots.length,0);});
test('application rolls back earlier targets after write failure',()=>{const T=host().ThreadMatch,d=document(),original=rgb(1,2,3),obj=p(original),bad=p(original);Object.defineProperty(bad,'fillColor',{get(){return original;},set(){throw Error('locked');}});assert.throws(()=>T.applyThread(d,{targets:[{kind:'path',item:obj},{kind:'path',item:bad}]},thread));assert.equal(obj.fillColor,original);assert.equal(d.spots[0].removed,true);});
test('label is an editable group with color chip, bold name and hash code',()=>{const h=host(),T=h.ThreadMatch,d=document(),shapes=[],frames=[];h.app.textFonts={getByName(n){return {name:n};}};d.groupItems={add(){return {pathItems:{rectangle(top,left,width,height){const p={top,left,width,height};shapes.push(p);return p;}},textFrames:{add(){const f={textRange:{characterAttributes:{}},geometricBounds:[0,20,80,0]};frames.push(f);return f;}},remove(){}};}};const group=T.createThreadLabel(d,{targets:[{kind:'path',item:{geometricBounds:[10,80,100,20]}}]},thread);assert.equal(group.name,'ThreadMatch 5924 · lemon');assert.equal(shapes.length,2);assert.equal(shapes[0].top,2);assert.equal(shapes[0].fillColor.red,255);assert.equal(shapes[1].fillColor.red,200);assert.equal(frames[0].contents,'Lemon');assert.equal(frames[0].textRange.characterAttributes.textFont.name,'Arial-BoldMT');assert.equal(frames[0].textRange.characterAttributes.fillColor.red,0);assert.equal(frames[1].contents,'#5924');});
