const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
function environment({depth=1,exposed=true,existing=false,locked=false,commandFails=false,stuck=false}={}){
 const calls=[],groups=[],h={RGBColor:function(){},PointType:{CORNER:'corner'},app:{textFonts:{getByName(){return {};}}}};
 vm.createContext(h);for(const f of ['color/convert.js','illustrator/selection.js','illustrator/swatches.js','illustrator/threadIconData.js','illustrator/threadIcon.js','illustrator/labels.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../src',f),'utf8'),h);
 function group(){const g={pathItems:{rectangle(){return {};},add(){const p={pathPoints:[]};p.pathPoints.add=function(){const q={};this.push(q);return q;};return p;}},textFrames:{add(){return {textRange:{characterAttributes:{}},geometricBounds:[0,0,60,-20]};}},groupItems:{add:group},compoundPathItems:{add:group},remove(){}};return g;}
 const doc={typename:'Document',groupItems:groups},ancestor={typename:'GroupItem',parent:doc};Object.defineProperty(ancestor,'isIsolated',{get(){return exposed&&depth>0;}});
 const item={typename:'PathItem',parent:ancestor,geometricBounds:[10,80,100,20]},selection=[item];doc.selection=selection;
 const layer={typename:'Layer',parent:doc,locked,visible:true,groupItems:{add(){const g=group();groups.push(g);return g;}}};let output=existing?layer:null;
 doc.layers={getByName(){if(!output)throw Error('missing');return output;},add(){calls.push('add');if(depth)throw Error("Cannot add a new layer as sibling to 'Isolation Mode' synthetic layer.");output=layer;return layer;}};
 Object.defineProperty(doc,'activeLayer',{get(){return depth&&exposed?{typename:'Layer',name:'Isolation Mode',parent:doc}:layer;}});
 h.app.executeMenuCommand=function(command){calls.push(command);if(commandFails)throw Error('PARM');if(!stuck)depth--;doc.selection=[];};
 return {T:h.ThreadMatch,doc,item,selection,calls,groups,layer,bucket:{targets:[{kind:'path',item}]},thread:{code:'5924',name:'lemon',rgb:{r:200,g:180,b:0}}};
}
for(const template of ['classic','spool'])test(template+' label exits nested isolation and retains selected objects',()=>{const e=environment({depth:2}),g=e.T.createThreadLabel(e.doc,e.bucket,e.thread,{template});assert.equal(e.calls.filter(c=>c==='exitFocus').length,2);assert.deepEqual(Array.from(e.doc.selection),e.selection);assert.equal(e.groups.length,1);assert.equal(e.layer.name,'ThreadMatch · Producción');assert.match(g.note,/ThreadMatch.label/);});
test('legend can use existing production layer after leaving isolation',()=>{const e=environment({existing:true}),g=e.T.createLegend(e.doc,[e.bucket],[e.thread],{},'isolation-test','pdf');assert.deepEqual(e.calls,['exitFocus']);assert.equal(e.groups.length,1);assert.match(g.note,/ThreadMatch.legend/);});
test('native synthetic-layer error retries output creation when isolation is not exposed',()=>{const e=environment({exposed:false});e.T.createThreadLabel(e.doc,e.bucket,e.thread);assert.deepEqual(e.calls,['add','exitFocus','add']);assert.equal(e.groups.length,1);assert.deepEqual(Array.from(e.doc.selection),e.selection);});
test('normal output does not issue isolation commands or change selection',()=>{const e=environment({depth:0});e.T.outputGroup(e.doc);assert.deepEqual(e.calls,['add']);assert.equal(e.doc.selection,e.selection);});
test('unsupported exit command stops before creating output and explains Esc',()=>{const e=environment({commandFails:true});assert.throws(()=>e.T.createThreadLabel(e.doc,e.bucket,e.thread),/aislamiento con Esc/);assert.equal(e.groups.length,0);assert.deepEqual(e.calls,['exitFocus']);});
test('a host that cannot leave isolation has a bounded retry and no partial label',()=>{const e=environment({stuck:true});assert.throws(()=>e.T.createThreadLabel(e.doc,e.bucket,e.thread),/aislamiento con Esc/);assert.equal(e.groups.length,0);assert.equal(e.calls.length,32);});
test('locked production layer is never unlocked and does not trigger exit commands',()=>{const e=environment({depth:0,existing:true,locked:true});assert.throws(()=>e.T.outputGroup(e.doc),/Desbloquea/);assert.equal(e.groups.length,0);assert.deepEqual(e.calls,[]);assert.equal(e.layer.locked,true);});
