const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');
function run(button,colors=5){const elements=[];function control(type,text){const c={type,text,children:[],graphics:{BrushType:{SOLID_COLOR:1},rectPath(){},fillPath(){},newBrush(){}},size:{width:54,height:48},add(t,b,s){if(t==='dropdownlist'){const select=control(t,s);let current;Object.defineProperty(select,'selection',{get(){return current;},set(v){current=typeof v==='number'?select.children[v]:v;}});select.add=function(_,label){const item={text:label,index:this.children.length};this.children.push(item);return item;};this.children.push(select);return select;}const child=control(t,s);this.children.push(child);return child;},notify(){throw Error('Do not paint before the window is shown');},layout:{layout(){}},close(){},show(){elements.find(e=>e.text===button).onClick();}};elements.push(c);return c;}const ctx={Window:function(){return control('dialog','ThreadMatch');}};vm.createContext(ctx);for(const f of ['color/convert.js','color/deltaE2000.js','matching/matcher.js','ui/matcherDialog.js'])vm.runInContext(fs.readFileSync(path.join(root,'src',f),'utf8'),ctx);const t={code:'5924',name:'lemon',rgb:{r:190,g:180,b:0}},bucket={rgb:{r:200,g:180,b:0},hex:'#C8B400',targets:[{}]},a={groups:[bucket],skipped:0};const result=ctx.ThreadMatch.showMatcherDialog(a,()=>Array.from({length:colors},()=>({thread:t,code:t.code,name:t.name,deltaE:2})));return result;}
test('ScriptUI initializes and selects apply action',()=>assert.equal(run('Aplicar hilo').action,'apply'));
test('ScriptUI initializes and selects label action',()=>assert.equal(run('Crear etiqueta').action,'label'));
test('ScriptUI supports catalogs containing fewer than five results',()=>assert.equal(run('Aplicar hilo',1).thread.code,'5924'));
test('portable CommonJS engine exposes matching API',()=>{const T=require('../dist/threadmatch-core.js');assert.equal(T.findClosestMadeiraColors({r:22,g:87,b:171},5).length,5);});
test('JSX contains ASCII only and startup errors identify the stage',()=>{const s=fs.readFileSync(path.join(root,'dist/ThreadMatch.jsx'),'utf8');assert.ok(!/[^\x00-\x7F]/.test(s));let message;vm.runInNewContext(s.replace(/^#target illustrator\n/,''),{app:{documents:[]},alert:m=>message=m});assert.ok(message.includes('Abre un documento'));assert.ok(message.includes('Etapa: Inicio'));});
test('host error details are retained instead of replaced by a generic alert',()=>{const s=fs.readFileSync(path.join(root,'dist/ThreadMatch.jsx'),'utf8').replace(/^#target illustrator\n/,'');let message;const app={documents:[{}],get activeDocument(){const e=Error('Host diagnostic example');e.number=123;e.line=77;throw e;}};vm.runInNewContext(s,{app,alert:m=>message=m});assert.ok(message.includes('Host diagnostic example'));assert.ok(message.includes('Código: 123'));assert.ok(message.includes('Línea: 77'));});
