(function(T){
 T.outputSignature=function(group){var parts=[],items=group.pageItems||[],i,item;parts.push(group.note||'',group.name||'',String(group.geometricBounds||''));for(i=0;i<items.length;i++){item=items[i];parts.push(item.typename,item.contents||'',String(item.geometricBounds||''));try{if(item.fillColor)parts.push(T.rgbToHex(T.illustratorColorToRGB(item.fillColor)));if(item.textRange)parts.push(item.textRange.characterAttributes.size,T.rgbToHex(T.illustratorColorToRGB(item.textRange.characterAttributes.fillColor)));}catch(ignore){parts.push('unsupported');}}return parts.join('|');};
 T.beginTransaction=function(doc,entries){
  var records=[],created=[],swatches={},i,j,entry,target,swatch,transaction;
  try{for(i=0;i<entries.length;i++){entry=entries[i];swatch=swatches[entry.thread.code];if(!swatch){swatch=T.getThreadSwatch(doc,entry.thread);swatches[entry.thread.code]=swatch;if(swatch.created)created.push({spot:swatch.spot,removed:false});}for(j=0;j<entry.bucket.targets.length;j++){target=entry.bucket.targets[j];records.push({target:target,before:T.captureFill(target),after:swatch.color,written:false,restored:false});}}}
  catch(e){for(i=0;i<created.length;i++){try{created[i].spot.remove();}catch(ignore){}}throw e;}
  transaction={doc:doc,records:records,created:created,group:null,previousGroup:null,previousHidden:false,
   apply:function(){for(var k=0;k<records.length;k++){records[k].written=true;T.setTargetFill(records[k].target,records[k].after);}},
   rollback:function(){var failures=0,k;for(k=records.length-1;k>=0;k--){if(!records[k].written||records[k].restored)continue;try{T.restoreFill(records[k].target,records[k].before);records[k].restored=true;}catch(ignore){failures++;}}if(transaction.group){try{transaction.group.remove();transaction.group=null;}catch(ignore2){failures++;}}if(transaction.previousGroup){try{transaction.previousGroup.hidden=transaction.previousHidden;transaction.previousGroup=null;}catch(ignore3){failures++;}}if(!failures){for(k=0;k<created.length;k++){try{if(!created[k].removed){created[k].spot.remove();created[k].removed=true;}}catch(ignore4){failures++;}}}return failures;},
   validateRecovery:function(){if(transaction.group&&(transaction.group.locked||transaction.group.hidden||T.outputSignature(transaction.group)!==transaction.groupSignature))throw Error('Cambió la leyenda después de crearla. La recuperación no la eliminará.');for(var k=0;k<records.length;k++){var r=records[k];if(!r.written||r.restored)continue;var target=r.target,owner=target.frame||target.item;if(owner.locked||owner.hidden||owner.editable===false)throw Error('Un objeto de recuperación está bloqueado u oculto.');var expected=T.rgbToHex(T.illustratorColorToRGB(r.after));if(target.kind==='compound'){if(target.item.pathItems.length!==r.before.length)throw Error('Cambió un trazado compuesto.');for(var n=0;n<r.before.length;n++)if(T.rgbToHex(T.illustratorColorToRGB(target.item.pathItems[n].fillColor))!==expected)throw Error('Cambió un objeto después de aplicar. La recuperación no lo sobrescribirá.');}else if(T.rgbToHex(T.illustratorColorToRGB(T.getTargetFill(target)))!==expected)throw Error('Cambió un relleno después de aplicar. La recuperación no lo sobrescribirá.');}}
  };return transaction;
 };
}(ThreadMatch));
