const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'../..');
function env(){const obj={typename:'PathItem',filled:true,fillColor:{typename:'RGBColor',red:20,green:80,blue:170}},doc={selection:[obj]},app={documents:[doc],activeDocument:doc,redraw(){}};const c={app,RGBColor:function(){this.typename='RGBColor'},SpotColor:function(){this.typename='SpotColor'},ColorModel:{PROCESS:'process'}};vm.createContext(c);vm.runInContext(fs.readFileSync(path.join(root,'plugin/com.threadmatch.illustrator/jsx/host.jsx'),'utf8'),c);return {api:c.ThreadMatchCEP,doc,obj,app,context:c};}
test('scan returns 5 ranked matches and JSON-safe names',()=>{const e=env(),r=JSON.parse(e.api.scan());assert.equal(r.ok,true);assert.equal(r.groups.length,1);assert.equal(r.groups[0].matches.length,5);for(let i=1;i<5;i++)assert.ok(r.groups[0].matches[i].deltaE>=r.groups[0].matches[i-1].deltaE);});
test('no document and empty selection return useful messages',()=>{const e=env();e.app.documents=[];assert.match(JSON.parse(e.api.scan()).error,/Abre un documento/);e.app.documents=[e.doc];e.doc.selection=[];assert.match(JSON.parse(e.api.scan()).error,/Selecciona/);});
test('persistent panel rejects stale token, document and selection',()=>{const e=env(),r=JSON.parse(e.api.scan());assert.equal(JSON.parse(e.api.act(r.token+1,0,'5924','apply')).ok,false);e.doc.selection=[];assert.match(JSON.parse(e.api.act(r.token,0,'5924','apply')).error,/selección/);e.doc.selection=[e.obj];e.app.activeDocument={};assert.match(JSON.parse(e.api.act(r.token,0,'5924','apply')).error,/documento/);});
test('changed fills cannot be overwritten from an old scan',()=>{const e=env(),r=JSON.parse(e.api.scan());e.obj.fillColor.red=200;assert.match(JSON.parse(e.api.act(r.token,0,'5924','apply')).error,/relleno/);assert.equal(e.obj.fillColor.red,200);});
test('invalid action, code and bucket are rejected',()=>{const e=env(),r=JSON.parse(e.api.scan());for(const args of [[r.token,0,'9999','apply'],[r.token,0,'5924','bad'],[r.token,4,'5924','apply'],[r.token,.5,'5924','apply']])assert.equal(JSON.parse(e.api.act(...args)).ok,false);});
test('apply uses the host swatch and invalidates the consumed scan',()=>{const e=env();e.doc.swatches=[];e.doc.spots={add(){return {remove(){}};}};const r=JSON.parse(e.api.scan()),applied=JSON.parse(e.api.act(r.token,0,r.groups[0].matches[0].code,'apply'));assert.equal(applied.ok,true);assert.equal(e.obj.fillColor.typename,'SpotColor');assert.equal(JSON.parse(e.api.act(r.token,0,'5924','apply')).ok,false);});
test('label bridge creates the approved grouped layout',()=>{const e=env();e.obj.geometricBounds=[0,40,50,0];let shapes=0;const text=[];e.doc.groupItems={add(){return {pathItems:{rectangle(){shapes++;return {};}},textFrames:{add(){const f={textRange:{characterAttributes:{}},geometricBounds:[0,0,40,-12]};text.push(f);return f;}},remove(){}};}};const r=JSON.parse(e.api.scan()),result=JSON.parse(e.api.act(r.token,0,'5990','label'));assert.equal(result.ok,true);assert.equal(shapes,2);assert.equal(text[0].contents,'Azalea');assert.equal(text[1].contents,'#5990');assert.equal(e.obj.fillColor.red,20);});
test('watch keeps the token for unchanged selection and refreshes on fill changes',()=>{const e=env(),r=JSON.parse(e.api.watch());assert.equal(r.ok,true);assert.equal(JSON.parse(e.api.watch()).unchanged,true);e.obj.fillColor.red=100;const next=JSON.parse(e.api.watch());assert.ok(next.token>r.token);assert.equal(next.groups[0].rgb.r,100);});
test('watch notices different objects having the same fill',()=>{const e=env(),r=JSON.parse(e.api.watch());e.doc.selection=[{...e.obj}];const next=JSON.parse(e.api.watch());assert.ok(next.token>r.token);assert.equal(next.unchanged,undefined);});
test('switching references recalculates matching and invalidates old actions',()=>{const e=env();e.obj.fillColor={typename:'RGBColor',red:255,green:255,blue:255};const pdf=JSON.parse(e.api.scan('pdf')),montage=JSON.parse(e.api.watch('montage'));assert.equal(montage.reference,'montage');assert.ok(montage.token>pdf.token);assert.equal(montage.groups[0].matches[0].code,'5801');assert.equal(montage.groups[0].matches[0].hex,'#FFFFFF');assert.equal(montage.groups[0].matches[0].deltaE,0);assert.equal(JSON.parse(e.api.act(pdf.token,0,'5801','apply')).ok,false);assert.equal(JSON.parse(e.api.watch('montage')).unchanged,true);const back=JSON.parse(e.api.watch('pdf'));assert.ok(back.token>montage.token);assert.ok(back.groups[0].matches[0].deltaE>0);assert.equal(JSON.parse(e.api.scan('invalid')).ok,false);});
test('montage applies adjusted white rather than the PDF value',()=>{const e=env();e.doc.swatches=[];e.doc.spots={add(){return {remove(){}};}};const r=JSON.parse(e.api.scan('montage'));assert.equal(JSON.parse(e.api.act(r.token,0,'5801','apply')).ok,true);assert.equal(e.obj.fillColor.spot.name,'5801 · fluorescent white · montaje');assert.equal(e.obj.fillColor.spot.color.red,255);assert.equal(e.obj.fillColor.spot.color.green,255);assert.equal(e.obj.fillColor.spot.color.blue,255);});
function call(e,method,...args){return JSON.parse(vm.runInContext('ThreadMatchCEP.'+method+'('+args.map(a=>JSON.stringify(a)).join(',')+')',e.context));}
function writable(){const e=env();let spots=0;e.doc.swatches=[];e.doc.spots={add(){spots++;let removed=false;return {remove(){if(!removed)spots--;removed=true;}};}};e.spotCount=()=>spots;return e;}
function table(r){return r.groups.map(g=>({hex:g.hex,code:g.matches[0].code,reviewed:true,locked:false,exclude:false}));}
test('batch is idempotent and recovery restores original fills and swatches',()=>{const e=writable(),before=e.obj.fillColor,r=call(e,'scan'),a=table(r),id='test-operation-001';const first=call(e,'batch',r.token,a,'apply',{},id);assert.equal(first.ok,true);assert.equal(e.spotCount(),1);assert.deepEqual(call(e,'batch',r.token,a,'apply',{},id),first);assert.equal(e.spotCount(),1);assert.equal(call(e,'recover').ok,true);assert.equal(e.obj.fillColor,before);assert.equal(e.spotCount(),0);assert.equal(call(e,'health').recoverable,false);});
test('batch rejects unreviewed, duplicate, missing and stale assignments before writes',()=>{const e=writable(),r=call(e,'scan'),a=table(r);a[0].reviewed=false;assert.equal(call(e,'batch',r.token,a,'apply',{},'test-operation-002').ok,false);assert.equal(e.spotCount(),0);a[0].reviewed=true;a.push(a[0]);assert.equal(call(e,'batch',r.token,a,'apply',{},'test-operation-003').ok,false);e.obj.fillColor.red++;assert.equal(call(e,'batch',r.token,table(r),'apply',{},'test-operation-004').ok,false);assert.equal(e.spotCount(),0);});
test('recovery does not overwrite fills changed after apply',()=>{const e=writable(),r=call(e,'scan');assert.equal(call(e,'batch',r.token,table(r),'apply',{},'test-operation-005').ok,true);e.obj.fillColor={typename:'RGBColor',red:200,green:0,blue:0};assert.equal(call(e,'recover').ok,false);assert.equal(e.obj.fillColor.red,200);assert.equal(e.spotCount(),1);});
test('overlapping group and child roots are read once; locked outputs are omitted',()=>{const e=env(),group={typename:'GroupItem',pageItems:[e.obj]};e.obj.parent=group;e.doc.selection=[group,e.obj,{typename:'PathItem',locked:true},{typename:'GroupItem',note:'ThreadMatch.label.v1|5801',pageItems:[e.obj]}];const r=JSON.parse(e.api.scan());assert.equal(r.ok,true);assert.equal(r.groups[0].count,1);assert.equal(r.reasons['Bloqueado u oculto'],1);assert.equal(r.reasons['Salida ThreadMatch'],1);});
test('available filter affects suggestions and leaves arbitrary manual thread actions supported',()=>{const e=env(),r=JSON.parse(e.api.scan('pdf',{available:['5801']}));assert.equal(r.groups[0].matches.length,1);assert.equal(r.groups[0].matches[0].code,'5801');});
test('scope changes and artboard changes invalidate cached actions',()=>{const e=env();e.obj.geometricBounds=[0,100,50,50];e.doc.pageItems=[e.obj];let board=0;e.doc.artboards=[{artboardRect:[0,200,200,0]},{artboardRect:[0,200,200,0]}];e.doc.artboards.getActiveArtboardIndex=()=>board;const r=JSON.parse(e.api.scan('pdf',{scope:'artboard'}));board=1;assert.match(JSON.parse(e.api.act(r.token,0,'5801','label')).error,/mesa/);});
