const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'../..');
function env(){const obj={typename:'PathItem',filled:true,fillColor:{typename:'RGBColor',red:20,green:80,blue:170}},doc={selection:[obj]},app={documents:[doc],activeDocument:doc,redraw(){}};const c={app,RGBColor:function(){this.typename='RGBColor'},SpotColor:function(){this.typename='SpotColor'},ColorModel:{PROCESS:'process'}};vm.createContext(c);vm.runInContext(fs.readFileSync(path.join(root,'plugin/com.threadmatch.illustrator/jsx/host.jsx'),'utf8'),c);return {api:c.ThreadMatchCEP,doc,obj,app,context:c};}
test('scan returns 5 ranked matches and JSON-safe names',()=>{const e=env(),r=JSON.parse(e.api.scan());assert.equal(r.ok,true);assert.equal(r.groups.length,1);assert.equal(r.groups[0].matches.length,5);for(let i=1;i<5;i++)assert.ok(r.groups[0].matches[i].deltaE>=r.groups[0].matches[i-1].deltaE);});
test('no document and empty selection return useful messages',()=>{const e=env();e.app.documents=[];assert.match(JSON.parse(e.api.scan()).error,/Abre un documento/);e.app.documents=[e.doc];e.doc.selection=[];assert.match(JSON.parse(e.api.scan()).error,/Selecciona/);});
test('persistent panel rejects stale token, document and selection',()=>{const e=env(),r=JSON.parse(e.api.scan());assert.equal(JSON.parse(e.api.act(r.token+1,0,'5924','apply')).ok,false);e.doc.selection=[];assert.match(JSON.parse(e.api.act(r.token,0,'5924','apply')).error,/selección/);e.doc.selection=[e.obj];e.app.activeDocument={};assert.match(JSON.parse(e.api.act(r.token,0,'5924','apply')).error,/documento/);});
test('changed fills cannot be overwritten from an old scan',()=>{const e=env(),r=JSON.parse(e.api.scan());e.obj.fillColor.red=200;assert.match(JSON.parse(e.api.act(r.token,0,'5924','apply')).error,/relleno/);assert.equal(e.obj.fillColor.red,200);});
test('invalid action, code and bucket are rejected',()=>{const e=env(),r=JSON.parse(e.api.scan());for(const args of [[r.token,0,'9999','apply'],[r.token,0,'5924','bad'],[r.token,4,'5924','apply'],[r.token,.5,'5924','apply']])assert.equal(JSON.parse(e.api.act(...args)).ok,false);});
test('apply uses the host swatch and invalidates the consumed scan',()=>{const e=env();e.doc.swatches=[];e.doc.spots={add(){return {remove(){}};}};const r=JSON.parse(e.api.scan()),applied=JSON.parse(e.api.act(r.token,0,r.groups[0].matches[0].code,'apply'));assert.equal(applied.ok,true);assert.equal(e.obj.fillColor.typename,'SpotColor');assert.equal(JSON.parse(e.api.act(r.token,0,'5924','apply')).ok,false);});
test('label bridge creates the approved grouped layout',()=>{const e=env();e.obj.geometricBounds=[0,40,50,0];let shapes=0;const text=[];e.doc.groupItems={add(){return {pathItems:{rectangle(){shapes++;return {};}},textFrames:{add(){const f={textRange:{characterAttributes:{}},geometricBounds:[0,0,40,-12]};text.push(f);return f;}},remove(){}};}};const r=JSON.parse(e.api.scan()),result=JSON.parse(e.api.act(r.token,0,'5990','label'));assert.equal(result.ok,true);assert.equal(shapes,2);assert.equal(text[0].contents,'Azalea');assert.equal(text[1].contents,'#5990');assert.equal(e.obj.fillColor.red,20);});
test('watch keeps the token for unchanged selection and refreshes on fill changes',()=>{const e=env(),r=JSON.parse(e.api.watch());assert.equal(r.ok,true);assert.equal(JSON.parse(e.api.watch()).unchanged,true);e.obj.fillColor.red=100;const next=JSON.parse(e.api.watch());assert.ok(next.token>r.token);assert.equal(next.groups[0].rgb.r,100);});
test('watch notices different objects having the same fill',()=>{const e=env(),r=JSON.parse(e.api.watch());e.doc.selection=[{...e.obj}];const next=JSON.parse(e.api.watch());assert.ok(next.token>r.token);assert.equal(next.unchanged,undefined);});
test('switching references recalculates matching and invalidates old actions',()=>{const e=env();e.obj.fillColor={typename:'RGBColor',red:249,green:249,blue:249};const pdf=JSON.parse(e.api.scan('pdf')),montage=JSON.parse(e.api.watch('montage'));assert.equal(montage.reference,'montage');assert.ok(montage.token>pdf.token);assert.equal(montage.groups[0].matches[0].code,'5801');assert.equal(montage.groups[0].matches[0].hex,'#F9F9F9');assert.equal(montage.groups[0].matches[0].deltaE,0);assert.equal(JSON.parse(e.api.act(pdf.token,0,'5801','apply')).ok,false);assert.equal(JSON.parse(e.api.watch('montage')).unchanged,true);const back=JSON.parse(e.api.watch('pdf'));assert.ok(back.token>montage.token);assert.equal(back.groups[0].matches[0].deltaE,0);assert.equal(JSON.parse(e.api.scan('invalid')).ok,false);});
test('montage applies adjusted white rather than the PDF value',()=>{const e=env();e.doc.swatches=[];e.doc.spots={add(){return {remove(){}};}};const r=JSON.parse(e.api.scan('montage'));assert.equal(JSON.parse(e.api.act(r.token,0,'5801','apply')).ok,true);assert.equal(e.obj.fillColor.spot.name,'5801 · fluorescent white · #F9F9F9 · montaje');assert.equal(e.obj.fillColor.spot.color.red,249);assert.equal(e.obj.fillColor.spot.color.green,249);assert.equal(e.obj.fillColor.spot.color.blue,249);});
function call(e,method,...args){return JSON.parse(vm.runInContext('ThreadMatchCEP.'+method+'('+args.map(a=>JSON.stringify(a)).join(',')+')',e.context));}
function writable(){const e=env();e.doc.pageItems=e.doc.selection;let spots=0;e.doc.swatches=[];e.doc.spots={add(){spots++;let removed=false;return {remove(){if(!removed)spots--;removed=true;}};}};e.spotCount=()=>spots;return e;}
function table(r){return r.groups.map(g=>({hex:g.hex,code:g.matches[0].code,reviewed:true,locked:false,exclude:false}));}
test('batch is idempotent and recovery restores original fills and swatches',()=>{const e=writable(),before=e.obj.fillColor,r=call(e,'scan'),a=table(r),id='test-operation-001';const first=call(e,'batch',r.token,a,'apply',{},id);assert.equal(first.ok,true);assert.equal(e.spotCount(),1);assert.deepEqual(call(e,'batch',r.token,a,'apply',{},id),first);assert.equal(e.spotCount(),1);assert.equal(call(e,'recover').ok,true);assert.equal(e.obj.fillColor,before);assert.equal(e.spotCount(),0);assert.equal(call(e,'health').recoverable,false);});
test('batch rejects unreviewed, duplicate, missing and stale assignments before writes',()=>{const e=writable(),r=call(e,'scan'),a=table(r);a[0].reviewed=false;assert.equal(call(e,'batch',r.token,a,'apply',{},'test-operation-002').ok,false);assert.equal(e.spotCount(),0);a[0].reviewed=true;a.push(a[0]);assert.equal(call(e,'batch',r.token,a,'apply',{},'test-operation-003').ok,false);e.obj.fillColor.red++;assert.equal(call(e,'batch',r.token,table(r),'apply',{},'test-operation-004').ok,false);assert.equal(e.spotCount(),0);});
test('recovery does not overwrite fills changed after apply',()=>{const e=writable(),r=call(e,'scan');assert.equal(call(e,'batch',r.token,table(r),'apply',{},'test-operation-005').ok,true);e.obj.fillColor={typename:'RGBColor',red:200,green:0,blue:0};assert.equal(call(e,'recover').ok,false);assert.equal(e.obj.fillColor.red,200);assert.equal(e.spotCount(),1);});
test('overlapping group and child roots are read once; locked outputs are omitted',()=>{const e=env(),group={typename:'GroupItem',pageItems:[e.obj]};e.obj.parent=group;e.doc.selection=[group,e.obj,{typename:'PathItem',locked:true},{typename:'GroupItem',note:'ThreadMatch.label.v1|5801',pageItems:[e.obj]}];const r=JSON.parse(e.api.scan());assert.equal(r.ok,true);assert.equal(r.groups[0].count,1);assert.equal(r.reasons['Bloqueado u oculto'],1);assert.equal(r.reasons['Salida ThreadMatch'],1);});
test('available filter affects suggestions and leaves arbitrary manual thread actions supported',()=>{const e=env(),r=JSON.parse(e.api.scan('pdf',{available:['5801']}));assert.equal(r.groups[0].matches.length,1);assert.equal(r.groups[0].matches[0].code,'5801');});
test('scope changes and artboard changes invalidate cached actions',()=>{const e=env();e.obj.geometricBounds=[0,100,50,50];e.doc.pageItems=[e.obj];let board=0;e.doc.artboards=[{artboardRect:[0,200,200,0]},{artboardRect:[0,200,200,0]}];e.doc.artboards.getActiveArtboardIndex=()=>board;const r=JSON.parse(e.api.scan('pdf',{scope:'artboard'}));board=1;assert.match(JSON.parse(e.api.act(r.token,0,'5801','label')).error,/mesa/);});
test('partial write failure restores earlier targets before reporting failure',()=>{const e=writable(),first=e.obj.fillColor,second={typename:'PathItem',filled:true};let fill={typename:'RGBColor',red:22,green:80,blue:170},before=fill;Object.defineProperty(second,'fillColor',{get(){return fill;},set(value){if(value.typename==='SpotColor')throw Error('injected write failure');fill=value;}});e.doc.selection.push(second);const r=call(e,'scan'),out=call(e,'batch',r.token,table(r),'apply',{},'failure-operation-001');assert.equal(out.ok,false);assert.equal(e.obj.fillColor,first);assert.equal(second.fillColor,before);assert.equal(e.spotCount(),0);});
test('incomplete rollback blocks writes and can resume once obstruction clears',()=>{const e=writable(),first=e.obj.fillColor;let fill=first,rejectRestore=true;Object.defineProperty(e.obj,'fillColor',{get(){return fill;},set(value){if(value===first&&rejectRestore)throw Error('injected restore failure');fill=value;}});const second={typename:'PathItem',filled:true};let next={typename:'RGBColor',red:40,green:80,blue:170};Object.defineProperty(second,'fillColor',{get(){return next;},set(value){if(value.typename==='SpotColor')throw Error('injected apply failure');next=value;}});e.doc.selection.push(second);const r=call(e,'scan'),out=call(e,'batch',r.token,table(r),'apply',{},'failure-operation-002');assert.equal(out.ok,false);assert.equal(out.recoverable,true);assert.match(out.error,/parcial/);assert.match(call(e,'act',r.token,0,'5801','apply').error,/recuperación pendiente/);rejectRestore=false;assert.equal(call(e,'recover').ok,true);assert.equal(e.obj.fillColor,first);assert.equal(e.spotCount(),0);});
function outputDocument(e){e.obj.geometricBounds=[0,100,50,50];const items=[];items.add=function(){const group={pageItems:[],name:'',note:'',hidden:false,remove(){items.splice(items.indexOf(group),1);},pathItems:{rectangle(y,x,w,h){const p={typename:'PathItem',geometricBounds:[x,y,x+w,y-h]};group.pageItems.push(p);return p;}},textFrames:{add(){const f={typename:'TextFrame',contents:'',textRange:{characterAttributes:{}},geometricBounds:[0,0,30,-12]};group.pageItems.push(f);return f;}}};Object.defineProperty(group,'geometricBounds',{get(){return [0,0,300,-200];}});items.push(group);return group;};e.doc.groupItems=items;return items;}
test('legend copy and explicit update preserve old output and recover the update',()=>{const e=env(),outputs=outputDocument(e),r=call(e,'scan');assert.equal(call(e,'batch',r.token,table(r),'legend',{},'legend-operation-001').ok,true);assert.equal(outputs.length,1);const old=outputs[0],id=old.note.split('|')[1];const next=call(e,'scan');assert.equal(next.legends[0].id,id);assert.equal(call(e,'batch',next.token,table(next),'legend',{replaceLegendId:id},'legend-operation-002').ok,true);assert.equal(outputs.length,2);assert.equal(old.hidden,true);assert.equal(call(e,'recover').ok,true);assert.equal(outputs.length,1);assert.equal(old.hidden,false);});
test('recovery refuses to remove an edited production legend',()=>{const e=env(),outputs=outputDocument(e),r=call(e,'scan');assert.equal(call(e,'batch',r.token,table(r),'legend',{},'legend-operation-003').ok,true);outputs[0].textFrames;outputs[0].pageItems.find(x=>x.typename==='TextFrame').contents='Edited after operation';assert.match(call(e,'recover').error,/leyenda/);assert.equal(outputs.length,1);});

test('recovery preserves a new global swatch reused elsewhere after the operation',()=>{const e=writable(),r=call(e,'scan');assert.equal(call(e,'batch',r.token,table(r),'apply',{},'shared-swatch-001').ok,true);const other={typename:'PathItem',filled:true,fillColor:e.obj.fillColor};e.doc.pageItems.push(other);const restored=call(e,'recover');assert.equal(restored.ok,true);assert.equal(restored.keptSwatches,1);assert.equal(e.spotCount(),1);assert.equal(other.fillColor.typename,'SpotColor');assert.equal(e.obj.fillColor.typename,'RGBColor');});

test('partial manual recovery blocks subsequent writes until recovery completes',()=>{const e=env(),outputs=outputDocument(e),r=call(e,'scan');assert.equal(call(e,'batch',r.token,table(r),'legend',{},'legend-recovery-004').ok,true);const output=outputs[0],remove=output.remove;output.remove=function(){throw Error('injected removal failure');};assert.equal(call(e,'recover').ok,false);const next=call(e,'scan');assert.match(call(e,'act',next.token,0,'5801','label').error,/recuperación pendiente/);output.remove=remove;assert.equal(call(e,'recover').ok,true);assert.equal(outputs.length,0);});
