const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'../..');
function env(){const obj={typename:'PathItem',filled:true,fillColor:{typename:'RGBColor',red:20,green:80,blue:170}},doc={selection:[obj]},app={documents:[doc],activeDocument:doc,redraw(){}};const c={app,RGBColor:function(){this.typename='RGBColor'},SpotColor:function(){this.typename='SpotColor'},ColorModel:{PROCESS:'process'}};vm.createContext(c);vm.runInContext(fs.readFileSync(path.join(root,'plugin/com.threadmatch.illustrator/jsx/host.jsx'),'utf8'),c);return {api:c.ThreadMatchCEP,doc,obj,app};}
test('scan returns 5 ranked matches and JSON-safe names',()=>{const e=env(),r=JSON.parse(e.api.scan());assert.equal(r.ok,true);assert.equal(r.groups.length,1);assert.equal(r.groups[0].matches.length,5);for(let i=1;i<5;i++)assert.ok(r.groups[0].matches[i].deltaE>=r.groups[0].matches[i-1].deltaE);});
test('no document and empty selection return useful messages',()=>{const e=env();e.app.documents=[];assert.match(JSON.parse(e.api.scan()).error,/Abre un documento/);e.app.documents=[e.doc];e.doc.selection=[];assert.match(JSON.parse(e.api.scan()).error,/Selecciona/);});
test('persistent panel rejects stale token, document and selection',()=>{const e=env(),r=JSON.parse(e.api.scan());assert.equal(JSON.parse(e.api.act(r.token+1,0,'5924','apply')).ok,false);e.doc.selection=[];assert.match(JSON.parse(e.api.act(r.token,0,'5924','apply')).error,/selección/);e.doc.selection=[e.obj];e.app.activeDocument={};assert.match(JSON.parse(e.api.act(r.token,0,'5924','apply')).error,/documento/);});
test('changed fills cannot be overwritten from an old scan',()=>{const e=env(),r=JSON.parse(e.api.scan());e.obj.fillColor.red=200;assert.match(JSON.parse(e.api.act(r.token,0,'5924','apply')).error,/relleno/);assert.equal(e.obj.fillColor.red,200);});
test('invalid action, code and bucket are rejected',()=>{const e=env(),r=JSON.parse(e.api.scan());for(const args of [[r.token,0,'9999','apply'],[r.token,0,'5924','bad'],[r.token,4,'5924','apply'],[r.token,.5,'5924','apply']])assert.equal(JSON.parse(e.api.act(...args)).ok,false);});
test('apply uses the host swatch and invalidates the consumed scan',()=>{const e=env();e.doc.swatches=[];e.doc.spots={add(){return {remove(){}};}};const r=JSON.parse(e.api.scan()),applied=JSON.parse(e.api.act(r.token,0,r.groups[0].matches[0].code,'apply'));assert.equal(applied.ok,true);assert.equal(e.obj.fillColor.typename,'SpotColor');assert.equal(JSON.parse(e.api.act(r.token,0,'5924','apply')).ok,false);});
test('label bridge creates the approved grouped layout',()=>{const e=env();e.obj.geometricBounds=[0,40,50,0];let shapes=0;const text=[];e.doc.groupItems={add(){return {pathItems:{rectangle(){shapes++;return {};}},textFrames:{add(){const f={textRange:{characterAttributes:{}},geometricBounds:[0,0,40,-12]};text.push(f);return f;}},remove(){}};}};const r=JSON.parse(e.api.scan()),result=JSON.parse(e.api.act(r.token,0,'5990','label'));assert.equal(result.ok,true);assert.equal(shapes,2);assert.equal(text[0].contents,'Azalea');assert.equal(text[1].contents,'#5990');assert.equal(e.obj.fillColor.red,20);});
test('watch keeps the token for unchanged selection and refreshes on fill changes',()=>{const e=env(),r=JSON.parse(e.api.watch());assert.equal(r.ok,true);assert.equal(JSON.parse(e.api.watch()).unchanged,true);e.obj.fillColor.red=100;const next=JSON.parse(e.api.watch());assert.ok(next.token>r.token);assert.equal(next.groups[0].rgb.r,100);});
test('watch notices different objects having the same fill',()=>{const e=env(),r=JSON.parse(e.api.watch());e.doc.selection=[{...e.obj}];const next=JSON.parse(e.api.watch());assert.ok(next.token>r.token);assert.equal(next.unchanged,undefined);});
