(function(){
 'use strict';var $=function(id){return document.getElementById(id);},state=null,selected=null,busy=false,polling=false,pending=null,writing=false,locked=false,alive=true,timer=null,generation=0,noticeUntil=0,lastInteraction=Date.now(),page=0,favoritePage=0,designPage=0,manual=false,assignments=[],metrics={},releaseURL=null,lastClearMessage=null;
 var storage;try{storage=window.localStorage;}catch(e){storage=null;}
 var base=(window.ThreadMatchCatalog||{}).pdf||[],store=window.ThreadMatchWorkspace.create(storage,base,window.ThreadMatch),prefs=store.get(),catalog=base;
 var favorites=window.ThreadMatchFavorites.create(storage,base.map(function(t){return t.code;}));
 function status(message,error,hold){if(!error&&!hold&&Date.now()<noticeUntil)return;if($('status').textContent!==message)$('status').textContent=message;if($('status').title!==message)$('status').title=message;var cls=error?'error':'';if($('status').className!==cls)$('status').className=cls;if(hold)noticeUntil=Date.now()+3000;}
 function savePrefs(){var persisted=store.save(prefs);if(!persisted)status('Opciones conservadas solo durante esta sesión: almacenamiento no disponible.',true,true);return persisted;}
 function source(){return state&&state.groups[Number($('colors').value)];}
 function currentAssignment(){return assignments[Number($('colors').value)];}
 function readyBatch(){return !!state&&assignments.some(function(a){return !a.exclude;})&&assignments.every(function(a){return a.exclude||a.code&&a.reviewed;});}
 function disable(id,value){var el=typeof id==='string'?$(id):id;value=!!value;if(el.disabled!==value)el.disabled=value;}
 function controls(){var disabled=busy&&!polling||locked;['apply','label','label-preview-create','search-apply','search-label','favorite-apply','favorite-label'].forEach(function(id){disable(id,disabled||!state||!selected);});['scan','reference','scope','reduce','review-all'].forEach(function(id){disable(id,disabled||(id==='reduce'&&!state));});disable('colors',disabled||!state);['batch-apply','batch-legend','batch-both'].forEach(function(id){disable(id,disabled||!readyBatch());});['export-json','import-json','export-csv','export-svg','import-measured','export-diagnostics'].forEach(function(id){disable(id,disabled);});disable('recover',disabled||!metrics.recoverable);disable('health',busy&&!polling);document.querySelectorAll('.rows input,.rows button').forEach(function(el){disable(el,writing||locked);});}
 function finishRequest(){controls();var next=pending;pending=null;if(next&&!locked)next();}
 function clear(message){if(!state&&lastClearMessage===message)return;lastClearMessage=message;state=null;assignments=[];if(!manual)selected=null;$('colors').textContent='';var o=document.createElement('option');o.textContent='Selecciona un objeto';$('colors').appendChild(o);rows('matches',[],message);$('input-chip').style.backgroundColor='#484848';$('rgb').textContent='Match automático al cambiar de selección';$('context').textContent='—';if(!selected){$('preview-chip').style.backgroundColor='#777';$('preview-spool').style.color='#777';$('preview-name').textContent='Nombre del hilo';$('preview-code').textContent='#0000';}else preview();renderDesign();controls();}
 function request(method,args,callback,options){options=options||{};if(locked&&!options.health)return;if(busy){if(polling&&!options.background&&!pending)pending=function(){request(method,args,callback,options);};return;}if(!window.__adobe_cep__){clear('Abre ThreadMatch dentro de Illustrator.');status('Panel fuera de Illustrator.',true);return;}var script='ThreadMatchCEP.'+method+'('+args.map(function(a){return JSON.stringify(a);}).join(',')+')',id=++generation,started=Date.now();busy=true;polling=!!options.background;writing=['act','batch','recover','saveFile','openFile'].indexOf(method)!==-1;if(!polling)controls();
  var deadline=setTimeout(function(){if(id!==generation)return;generation++;busy=false;polling=false;writing=false;locked=true;status('Illustrator no confirmó la operación. Usa Más > Diagnóstico > Reconectar antes de escribir.',true,true);finishRequest();},options.dialog?600000:10000);
  function complete(raw){if(id!==generation)return;clearTimeout(deadline);busy=false;polling=false;writing=false;metrics.bridgeMs=Date.now()-started;var result;try{result=JSON.parse(raw);}catch(e){locked=true;status('Respuesta inválida de Illustrator. Usa Reconectar.',true,true);finishRequest();return;}
   if(result.recoverable!==undefined)metrics.recoverable=result.recoverable;if(!result.ok){if(method==='scan'||method==='watch')clear(result.error||'Selecciona un relleno sólido.');status(result.error,true,true);finishRequest();return;}if(options.health)locked=false;try{callback(result);}catch(e){status(e.message,true,true);}finishRequest();}
  try{window.__adobe_cep__.evalScript(script,complete);}catch(e){clearTimeout(deadline);generation++;busy=false;polling=false;writing=false;locked=true;status(e.message,true,true);finishRequest();}
 }
 function scanOptions(){return {scope:prefs.scope,available:prefs.onlyAvailable?prefs.available:null,measured:prefs.reference==='measured'?prefs.measured:null};}
 function scan(watch){if(locked||watch&&busy)return;request(watch?'watch':'scan',[prefs.reference,scanOptions()],load,{background:!!watch});}
 function tick(){if(!alive)return;if(!document.hidden&&$('auto').checked&&!busy&&!locked)scan(true);var rest=Math.min(5000,Date.now()-lastInteraction<5000?650:2500);timer=setTimeout(tick,Math.max(rest,(metrics.readMs||0)*4));}
 function find(code){return catalog.find(function(t){return t.code===code;});}
 function name(s){return s.charAt(0).toUpperCase()+s.slice(1);}
 function referenceName(){return prefs.reference==='pdf'?'Carta PDF':prefs.reference==='montage'?'Montaje · visual':'Lab medido';}
 function preview(){var spool=prefs.output.template==='spool';document.querySelector('.label-preview').classList.toggle('spool',spool);if(!selected)return;$('preview-spool').style.color=selected.hex;$('preview-chip').style.backgroundColor=selected.hex;$('preview-name').textContent=name(selected.name);$('preview-code').textContent='#'+selected.code;}
 function updateStar(button){var code=button.getAttribute('data-code'),saved=favorites.has(code);button.textContent=saved?'★':'☆';button.setAttribute('aria-pressed',String(saved));button.setAttribute('aria-label',(saved?'Quitar de favoritos el hilo ':'Añadir a favoritos el hilo ')+code);button.title=button.getAttribute('aria-label');}
 function star(code){var b=document.createElement('button');b.type='button';b.className='favorite-star';b.setAttribute('data-code',code);updateStar(b);b.addEventListener('click',function(e){e.preventDefault();e.stopPropagation();if(writing||locked)return;var r=favorites.toggle(code);document.querySelectorAll('.favorite-star').forEach(updateStar);renderFavorites();status('Hilo #'+code+(r.added?' añadido a favoritos.':' quitado de favoritos.')+(r.persisted?'':' Solo durante esta sesión.'),!r.persisted,true);});b.addEventListener('dblclick',function(e){e.preventDefault();e.stopPropagation();});return b;}
 function choose(thread,isManual){if(writing||locked)return;selected=thread;manual=isManual;var a=currentAssignment();if($('view').value==='design'&&a){a.code=thread.code;a.reviewed=false;a.exclude=false;renderDesign();}updateSelected();preview();controls();}
 function updateSelected(){document.querySelectorAll('.match').forEach(function(row){var input=row.querySelector('input');input.checked=!!selected&&input.value===selected.code;row.classList.toggle('selected',input.checked);});}
 function rows(id,items,emptyMessage){var list=$(id),signature=prefs.reference+'|'+emptyMessage+'|'+JSON.stringify(items.map(function(t){return [t.code,t.name,t.hex,t.deltaE,t.description,prefs.available.indexOf(t.code)!==-1];}));if(list.getAttribute('data-signature')===signature){updateSelected();return;}list.setAttribute('data-signature',signature);list.textContent='';items.forEach(function(thread){var row=document.createElement('div');row.className='match';row.title=thread.code+' · '+thread.name+' · '+thread.hex+' · '+referenceName()+(id==='matches'?'':' · elección manual');var radio=document.createElement('input');radio.type='radio';radio.name=id+'-thread';radio.value=thread.code;radio.setAttribute('aria-label',thread.code+' · '+name(thread.name));var chip=document.createElement('span');chip.className='chip';chip.style.backgroundColor=thread.hex;var text=document.createElement('div');text.className='thread-text';var title=document.createElement('b'),detail=document.createElement('small');title.textContent=thread.code+' · '+name(thread.name);detail.textContent=id==='matches'?thread.description:thread.hex+' · manual'+(prefs.available.indexOf(thread.code)!==-1?' · disponible':'');text.appendChild(title);text.appendChild(detail);row.appendChild(radio);row.appendChild(chip);row.appendChild(text);if(typeof thread.deltaE==='number'){var delta=document.createElement('span');delta.className='delta';delta.textContent=thread.deltaE.toFixed(2);row.appendChild(delta);}row.appendChild(star(thread.code));function select(){choose(thread,id!=='matches');}row.addEventListener('click',select);radio.addEventListener('change',select);row.addEventListener('dblclick',function(e){e.preventDefault();if(busy&&!polling||locked)return;select();act('label');});radio.addEventListener('keydown',function(e){if(e.key==='Enter'){e.preventDefault();select();act('label');}});list.appendChild(row);});if(!items.length){var empty=document.createElement('div');empty.className='empty';empty.textContent=emptyMessage;list.appendChild(empty);}updateSelected();}
 function render(previousCode){var g=source();if(!g)return;$('rgb').textContent='RGB '+Math.round(g.rgb.r)+' / '+Math.round(g.rgb.g)+' / '+Math.round(g.rgb.b);$('input-chip').style.backgroundColor=g.hex;if(!manual)selected=g.matches.find(function(t){return t.code===previousCode;})||g.matches[0]||null;rows('matches',g.matches,'No hay hilos disponibles para sugerir.');preview();search();renderFavorites();renderDesign();controls();}
 function load(result){var started=Date.now();Object.assign(metrics,result.metrics||{});if(result.unchanged){renderMetrics();return;}lastClearMessage=null;var old=state,oldHex=source()&&source().hex,oldAssignments=assignments,previousCode=selected&&selected.code,sameDoc=old&&old.documentId===result.documentId&&old.reference===result.reference&&old.scope===result.scope;
  if(old&&!sameDoc){manual=false;selected=null;oldAssignments=[];previousCode=null;}state=result;assignments=result.groups.map(function(g){var a=oldAssignments.find(function(a){return a.hex===g.hex;});return {hex:g.hex,code:a?a.code:g.matches[0]?g.matches[0].code:null,locked:a?!!a.locked:false,exclude:a?!!a.exclude:false,reviewed:false};});$('colors').textContent='';result.groups.forEach(function(g,i){var o=document.createElement('option');o.value=i;o.textContent=g.hex+' · '+g.count+' rellenos';$('colors').appendChild(o);if(g.hex===oldHex)$('colors').value=String(i);});var context=result.context||{};$('context').textContent=context.mode||'—';$('context').title='Modo: '+(context.mode||'No expuesto')+' · Perfil: '+(context.profile||'No expuesto');$('input-chip').title='Origen '+source().hex+' · '+referenceName();$('replace-legend').textContent='';var opt=document.createElement('option');opt.value='';opt.textContent='Crear copia nueva';$('replace-legend').appendChild(opt);(result.legends||[]).forEach(function(l){var o=document.createElement('option');o.value=l.id;o.textContent='Actualizar: '+l.name;$('replace-legend').appendChild(o);});render(previousCode);metrics.uiMs=Date.now()-started;metrics.reasons=result.reasons||{};renderMetrics();status(result.groups.length+' colores · '+(result.skipped?result.skipped+' omitidos':'selección sincronizada'));}
 function search(){var q=$('search-query').value.trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/^#/,'');var items=catalog.filter(function(t){return (t.code+' '+t.name).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').indexOf(q)!==-1;});var pages=Math.max(1,Math.ceil(items.length/5));page=Math.max(0,Math.min(page,pages-1));rows('catalog-results',items.slice(page*5,page*5+5),'No hay hilos con ese código o nombre.');$('search-count').textContent=items.length+' hilos · '+(page+1)+' / '+pages;$('previous-page').disabled=page===0;$('next-page').disabled=page===pages-1;}
 function renderFavorites(){var codes=$('saved-view').value==='recent'?prefs.recent:favorites.list(),items=codes.map(find).filter(Boolean),pages=Math.max(1,Math.ceil(items.length/5));favoritePage=Math.max(0,Math.min(favoritePage,pages-1));rows('favorite-results',items.slice(favoritePage*5,favoritePage*5+5),$('saved-view').value==='recent'?'Usa un hilo para añadirlo a Recientes.':'Aún no tienes favoritos. Marca ☆ en Hilos o Buscar para guardar un hilo.');$('favorite-total').textContent=items.length+' hilos';$('favorite-page').textContent=(favoritePage+1)+' / '+pages;$('favorite-previous').disabled=favoritePage===0;$('favorite-next').disabled=favoritePage===pages-1;}
 function remember(codes){codes.forEach(function(code){store.remember(code);});prefs=store.get();renderFavorites();}
 function outputOptions(){return Object.assign({},prefs.output,{title:prefs.title,replaceLegendId:$('replace-legend').value});}
 function act(action){if(busy&&!polling||locked||!state||!selected)return;var code=selected.code;request('act',[state.token,Number($('colors').value),code,action,outputOptions()],function(){remember([code]);status(action==='apply'?'Hilo #'+code+' aplicado.':'Etiqueta #'+code+' creada.',false,true);if(action==='apply')scan(false);});}
 function renderDesign(){var pages=Math.max(1,Math.ceil(assignments.length/5));designPage=Math.max(0,Math.min(designPage,pages-1));var list=$('design-results');list.textContent='';assignments.slice(designPage*5,designPage*5+5).forEach(function(a,n){var index=designPage*5+n,g=state.groups[index],t=find(a.code),row=document.createElement('div');row.className='assignment'+(index===Number($('colors').value)?' selected':'')+(a.exclude?' excluded':'');var chip=document.createElement('span');chip.className='chip';chip.style.backgroundColor=a.hex;chip.title='Origen '+a.hex;row.appendChild(chip);var body=document.createElement('div');body.className='thread-text';var title=document.createElement('b'),detail=document.createElement('small');title.textContent=a.hex+' → '+(a.code||'Sin hilo');var lab=t&&prefs.reference==='measured'?prefs.measured.colors.find(function(c){return c.code===a.code;}).lab:t&&ThreadMatch.rgbToLab({r:parseInt(t.hex.slice(1,3),16),g:parseInt(t.hex.slice(3,5),16),b:parseInt(t.hex.slice(5,7),16)});detail.textContent=(t?name(t.name):'Elige en Buscar')+(lab?' · ΔE '+ThreadMatch.deltaE2000(ThreadMatch.rgbToLab(g.rgb),lab).toFixed(2):'');body.appendChild(title);body.appendChild(detail);row.appendChild(body);row.title='Elegir otro hilo para '+a.hex;row.addEventListener('click',function(){if(writing||locked)return;$('colors').value=String(index);manual=true;selected=t;preview();updateSelected();renderDesign();tab(1);});function toggle(label,key,glyph){var b=document.createElement('button');b.textContent=glyph;b.title=label;b.setAttribute('aria-label',label+' '+a.hex);b.setAttribute('aria-pressed',String(!!a[key]));b.addEventListener('click',function(e){e.stopPropagation();if(writing||locked)return;a[key]=!a[key];renderDesign();controls();});row.appendChild(b);}toggle('Fijar hilo','locked','⌖');toggle('Excluir color','exclude','−');var check=document.createElement('input');check.type='checkbox';check.className='review-check';check.checked=a.reviewed;check.setAttribute('aria-label','Revisado '+a.hex);check.title='Revisado';check.addEventListener('click',function(e){e.stopPropagation();});check.addEventListener('change',function(){a.reviewed=check.checked;$('design-total').textContent=assignments.filter(function(a){return a.reviewed||a.exclude;}).length+'/'+assignments.length+' revisados';controls();});row.appendChild(check);list.appendChild(row);});if(!assignments.length){var empty=document.createElement('div');empty.className='empty';empty.textContent='Selecciona un diseño para preparar su paleta.';list.appendChild(empty);}$('design-total').textContent=assignments.length?assignments.filter(function(a){return a.reviewed||a.exclude;}).length+'/'+assignments.length+' revisados':'';$('design-page').textContent=(designPage+1)+' / '+pages;$('design-previous').disabled=designPage===0;$('design-next').disabled=designPage===pages-1;}
 function batch(action){if(!readyBatch())return;var codes=assignments.filter(function(a){return !a.exclude;}).map(function(a){return a.code;});var id='panel-'+Date.now()+'-'+Math.random().toString(36).slice(2,10);request('batch',[state.token,assignments,action,outputOptions(),id],function(){remember(codes);status('Operación de diseño completada. Recuperación disponible en Diagnóstico.',false,true);scan(false);});}
 var sections=['threads','search-panel','favorites-panel','label-settings'],tabs=['tab-threads','tab-search','tab-favorites','tab-label'];
 function tab(which){$('settings-panel').hidden=true;sections.forEach(function(id,i){$(id).hidden=which!==i;$(tabs[i]).setAttribute('aria-selected',String(which===i));$(tabs[i]).tabIndex=which===i?0:-1;});if(which===1)$('search-query').focus();}
 tabs.forEach(function(id,i){$(id).addEventListener('click',function(){tab(i);});$(id).addEventListener('keydown',function(e){if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();var next=(i+(e.key==='ArrowRight'?1:tabs.length-1))%tabs.length;tab(next);$(tabs[next]).focus();}});});
 function settingsPage(){document.querySelectorAll('[data-setting]').forEach(function(el){el.hidden=el.getAttribute('data-setting')!==$('settings-page').value;});renderMetrics();}
 function paletteList(){var list=$('palette-list');list.textContent='';prefs.palettes.forEach(function(p,i){var o=document.createElement('option');o.value=i;o.textContent=(p.client?p.client+' · ':'')+p.name+' · '+p.reference;list.appendChild(o);});$('load-palette').disabled=!prefs.palettes.length;$('delete-palette').disabled=!prefs.palettes.length;}
 function setCatalog(){if(prefs.reference==='measured'){var measured=ThreadMatch.measuredCatalog(ThreadMatch.catalog,prefs.measured);catalog=measured.colors;}else catalog=window.ThreadMatchCatalog[prefs.reference];$('reference').querySelector('[value=measured]').disabled=!prefs.measured;}
 function syncPrefs(){setCatalog();$('reference').value=prefs.reference;$('label-template').value=prefs.output.template;preview();$('scope').value=prefs.scope;$('job-title').value=prefs.title;$('client').value=prefs.client;$('only-available').checked=prefs.onlyAvailable;$('available-codes').value=prefs.available.join(', ');[['width-mm','widthMm'],['font-pt','fontPt'],['gap-mm','gapMm'],['columns','columns'],['placement','placement']].forEach(function(pair){$(pair[0]).value=prefs.output[pair[1]];});paletteList();search();renderFavorites();}
 function renderMetrics(){if($('settings-panel').hidden||$('settings-page').value!=='diagnostics')return;var m=metrics,message='Lectura: '+(m.readMs||0)+' ms · Ranking: '+(m.rankMs||0)+' ms\nPuente: '+(m.bridgeMs||0)+' ms · UI: '+(m.uiMs||0)+' ms\nVisitados: '+(m.visited||0)+' · Caché: '+(m.cache?m.cache.hits+' aciertos / '+m.cache.misses+' cálculos':'—')+'\nOmitidos: '+JSON.stringify(m.reasons||{})+'\nEstado: '+(locked?'confirmación pendiente':'conectado');if($('metrics').textContent!==message)$('metrics').textContent=message;}
 function saveFile(kind,content){request('saveFile',[kind,content],function(r){if(!r.cancelled)status('Archivo '+kind.toUpperCase()+' guardado.',false,true);},{dialog:true});}
 function importFile(callback){request('openFile',[],function(r){if(!r.cancelled)callback(JSON.parse(r.content));},{dialog:true});}
 function on(id,event,handler){$(id).addEventListener(event,function(e){try{handler(e);}catch(error){status(error.message,true,true);}});}
 on('scan','click',function(){scan(false);});on('colors','change',function(){manual=false;render();});on('auto','change',function(){if($('auto').checked)scan(false);});on('view','change',function(){$('color-view').hidden=$('view').value!=='color';$('design-view').hidden=$('view').value!=='design';renderDesign();controls();});
 ['apply','search-apply','favorite-apply'].forEach(function(id){on(id,'click',function(){act('apply');});});['label','search-label','favorite-label','label-preview-create'].forEach(function(id){on(id,'click',function(){act('label');});});
 on('search-query','input',function(){page=0;search();});on('previous-page','click',function(){page--;search();});on('next-page','click',function(){page++;search();});on('favorite-previous','click',function(){favoritePage--;renderFavorites();});on('favorite-next','click',function(){favoritePage++;renderFavorites();});on('saved-view','change',function(){favoritePage=0;renderFavorites();});on('design-previous','click',function(){designPage--;renderDesign();});on('design-next','click',function(){designPage++;renderDesign();});on('review-all','click',function(){assignments.forEach(function(a){if(a.code)a.reviewed=true;});renderDesign();controls();});
 on('reduce','click',function(){if(!state)return;request('reduce',[state.token,assignments,Number($('reduce-count').value),prefs.onlyAvailable?prefs.available:null],function(r){assignments=r.assignments;renderDesign();status('Propuesta reducida. Revisa las asignaciones antes de aplicar.',false,true);});});on('batch-apply','click',function(){batch('apply');});on('batch-legend','click',function(){batch('legend');});on('batch-both','click',function(){batch('both');});
 on('settings','click',function(){sections.forEach(function(id){$(id).hidden=true;});tabs.forEach(function(id){$(id).setAttribute('aria-selected','false');});$('settings-panel').hidden=false;settingsPage();});on('settings-page','change',settingsPage);
 on('reference','change',function(){prefs.reference=$('reference').value;savePrefs();var code=selected&&selected.code;setCatalog();selected=find(code);state=null;assignments=[];search();renderFavorites();preview();controls();document.querySelector('footer').textContent=prefs.reference==='montage'?'Montaje: ajuste visual · confirma con la carta física.':'Similitud digital · confirma con la carta física.';scan(false);});
 on('label-template','change',function(){prefs.output.template=$('label-template').value;savePrefs();preview();});on('scope','change',function(){prefs.scope=$('scope').value;savePrefs();state=null;assignments=[];scan(false);});on('job-title','change',function(){prefs.title=$('job-title').value;savePrefs();});on('client','change',function(){prefs.client=$('client').value;savePrefs();});
 [['width-mm','widthMm'],['font-pt','fontPt'],['gap-mm','gapMm'],['columns','columns'],['placement','placement']].forEach(function(pair){on(pair[0],'change',function(){var old=prefs.output[pair[1]];prefs.output[pair[1]]=pair[1]==='placement'?$(pair[0]).value:Number($(pair[0]).value);try{savePrefs();}catch(e){prefs.output[pair[1]]=old;$(pair[0]).value=old;throw e;}});});
 on('save-available','click',function(){var codes=$('available-codes').value.split(/[\s,;]+/).filter(Boolean);if(codes.some(function(code,i){return !base.some(function(t){return t.code===code;})||codes.indexOf(code)!==i;}))throw Error('Usa códigos válidos y sin duplicados.');prefs.available=codes;prefs.onlyAvailable=$('only-available').checked;savePrefs();state=null;assignments=[];search();renderFavorites();scan(false);status('Disponibilidad manual guardada.',false,true);});
 on('save-palette','click',function(){if(!state||!assignments.length||assignments.some(function(a){return !a.code;}))throw Error('Prepara primero las asignaciones del diseño.');var title=$('palette-name').value.trim();if(!title)throw Error('Escribe un nombre de paleta.');var p={name:title,client:prefs.client,reference:prefs.reference,assignments:JSON.parse(JSON.stringify(assignments))};var index=prefs.palettes.findIndex(function(p){return p.name===title&&p.client===prefs.client;});if(index>=0)prefs.palettes[index]=p;else prefs.palettes.push(p);savePrefs();paletteList();status('Paleta guardada.',false,true);});
 on('load-palette','click',function(){if(!state)throw Error('Selecciona primero el diseño.');var p=prefs.palettes[Number($('palette-list').value)];if(!p)throw Error('No hay paleta guardada.');if(p.reference!==prefs.reference)throw Error('Selecciona la referencia '+p.reference+' antes de cargar esta paleta.');var count=0;assignments=assignments.map(function(a){var saved=p.assignments.find(function(s){return s.hex===a.hex;});if(!saved)return a;count++;return Object.assign({},saved,{reviewed:false});});renderDesign();controls();status(count+' colores recuperados. Revisa antes de aplicar.',false,true);});on('delete-palette','click',function(){prefs.palettes.splice(Number($('palette-list').value),1);savePrefs();paletteList();});
 on('export-json','click',function(){saveFile('json',JSON.stringify(store.exportData(favorites.list()),null,2));});on('import-json','click',function(){importFile(function(data){prefs=store.importData(data,$('import-mode').value==='replace');favorites.reload();state=null;assignments=[];selected=null;manual=false;syncPrefs();scan(false);status('Respaldo importado.',false,true);});});
 on('import-measured','click',function(){importFile(function(data){ThreadMatch.measuredCatalog(ThreadMatch.catalog,data);prefs.measured=data;savePrefs();syncPrefs();status('Referencia Lab importada; ya puedes seleccionarla.',false,true);});});
 on('export-csv','click',function(){if(!state)throw Error('Selecciona un diseño.');saveFile('csv',ThreadMatchWorkspace.exportCSV(assignments,catalog,prefs.title,referenceName()));});on('export-svg','click',function(){if(!readyBatch())throw Error('Revisa las asignaciones antes de exportar.');saveFile('svg',ThreadMatchWorkspace.exportSVG(assignments,catalog,prefs.title,referenceName(),prefs.output));});
 on('health','click',function(){request('health',[],function(r){metrics.recoverable=r.recoverable;status('Illustrator confirmó la conexión. Selección actualizada.',false,true);renderMetrics();scan(false);},{health:true});});on('recover','click',function(){request('recover',[],function(r){metrics.recoverable=false;status('Operación recuperada.'+(r.keptSwatches?' Se conservan '+r.keptSwatches+' muestras usadas o no verificables.':''),false,true);scan(false);});});on('export-diagnostics','click',function(){saveFile('json',JSON.stringify({kind:'ThreadMatch.diagnostics',schemaVersion:1,version:window.ThreadMatchVersion,date:new Date().toISOString(),metrics:metrics,context:state?state.context:null,scope:prefs.scope},null,2));});
 var v=window.ThreadMatchVersion;$('version').textContent='ThreadMatch '+v.version+' · '+(v.channel==='pilot'?'piloto':'estable');
 on('check-update','click',function(){var button=$('check-update');button.disabled=true;var controller=new AbortController(),timeout=setTimeout(function(){controller.abort();},8000);fetch('https://api.github.com/repos/eguiajosue/thread-match/releases/latest',{signal:controller.signal,headers:{Accept:'application/vnd.github+json'}}).then(function(r){if(!r.ok)throw Error('No se pudo consultar GitHub ('+r.status+').');return r.json();}).then(function(r){if(r.prerelease||r.draft||!/^https:\/\/github\.com\/eguiajosue\/thread-match\/releases\/tag\/v[0-9.]+$/.test(r.html_url))throw Error('Respuesta de versión no válida.');releaseURL=r.html_url;$('open-release').disabled=false;$('update-info').textContent='Última estable: '+r.tag_name+'. Instalado: '+v.version+'. Consulta las notas de compatibilidad antes de instalar.';}).catch(function(e){status('Sin consulta de versiones: '+e.message,true,true);}).finally(function(){clearTimeout(timeout);button.disabled=false;});});on('open-release','click',function(){if(!releaseURL)return;if(window.cep&&window.cep.util)window.cep.util.openURLInDefaultBrowser(releaseURL);else window.open(releaseURL,'_blank','noopener');});
 window.addEventListener('storage',function(e){if(e.key===ThreadMatchFavorites.key||e.key===null){favorites.reload();document.querySelectorAll('.favorite-star').forEach(updateStar);renderFavorites();}});document.addEventListener('pointerdown',function(){lastInteraction=Date.now();});document.addEventListener('keydown',function(){lastInteraction=Date.now();});window.addEventListener('beforeunload',function(){alive=false;clearTimeout(timer);generation++;});document.addEventListener('visibilitychange',function(){if(!document.hidden&&$('auto').checked)scan(false);});
 syncPrefs();controls();if(window.__adobe_cep__){scan(false);timer=setTimeout(tick,650);}else{clear('Instala y abre el panel desde Illustrator.');status('Ventana > Extensiones > ThreadMatch',false);}
}());
