(function(){
 'use strict';var $=function(id){return document.getElementById(id);},state=null,selected=null,busy=false,timer=null,noticeUntil=0,alive=true,catalog=window.ThreadMatchCatalog||[],page=0,manual=false;
 function status(message,error,hold){if(!error&&!hold&&Date.now()<noticeUntil)return;$('status').textContent=message;$('status').title=message;$('status').className=error?'error':'';if(hold)noticeUntil=Date.now()+3000;}
 function controls(){['apply','label','label-preview-create','search-apply','search-label','colors'].forEach(function(id){$(id).disabled=busy||!state||(id!=='colors'&&!selected);});$('scan').disabled=busy;document.querySelectorAll('#matches input, #catalog-results input').forEach(function(el){el.disabled=busy;});}
 function clear(message){state=null;if(!manual)selected=null;$('colors').textContent='';var option=document.createElement('option');option.textContent='Selecciona un objeto';$('colors').appendChild(option);$('matches').textContent='';var empty=document.createElement('div');empty.className='empty';empty.textContent=message;$('matches').appendChild(empty);$('input-chip').style.backgroundColor='#484848';$('rgb').textContent='Match automático al cambiar de selección';$('preview-chip').style.backgroundColor='#777';$('preview-name').textContent='Nombre del hilo';$('preview-code').textContent='#0000';controls();}
 function request(script,callback){if(!window.__adobe_cep__){clear('Abre ThreadMatch dentro de Illustrator.');status('Panel fuera de Illustrator.',true);return;}busy=true;controls();try{window.__adobe_cep__.evalScript(script,function(raw){busy=false;var result;try{result=JSON.parse(raw);}catch(e){clear('Sin comunicación con Illustrator.');status(String(raw).slice(0,160),true);controls();return;}if(!result.ok){clear(result.error||'Selecciona un relleno sólido.');status(result.error,true);controls();return;}callback(result);controls();});}catch(e){busy=false;clear('No se pudo comunicar con Illustrator.');status(e.message,true);}}
 function name(s){return s.charAt(0).toUpperCase()+s.slice(1);}
 function preview(){if(!selected)return;$('preview-chip').style.backgroundColor=selected.hex;$('preview-name').textContent=name(selected.name);$('preview-code').textContent='#'+selected.code;}
 function render(previousCode){var group=state.groups[Number($('colors').value)];if(!group)return;$('rgb').textContent='RGB '+Math.round(group.rgb.r)+' / '+Math.round(group.rgb.g)+' / '+Math.round(group.rgb.b);$('input-chip').style.backgroundColor=group.hex;var list=$('matches');list.textContent='';if(!manual){selected=group.matches[0];group.matches.forEach(function(t){if(t.code===previousCode)selected=t;});}group.matches.forEach(function(thread){var row=document.createElement('label');row.className='match'+(thread===selected?' selected':'');row.title=thread.code+' · '+name(thread.name)+' — doble clic para crear etiqueta';var radio=document.createElement('input');radio.type='radio';radio.name='thread';radio.checked=thread===selected;radio.value=thread.code;var chip=document.createElement('span');chip.className='chip';chip.style.backgroundColor=thread.hex;var text=document.createElement('div');text.className='thread-text';var title=document.createElement('b'),detail=document.createElement('small'),delta=document.createElement('span');title.textContent=thread.code+' · '+name(thread.name);detail.textContent=thread.description;delta.className='delta';delta.textContent=thread.deltaE.toFixed(2);text.appendChild(title);text.appendChild(detail);row.appendChild(radio);row.appendChild(chip);row.appendChild(text);row.appendChild(delta);function choose(){if(busy)return;manual=false;selected=thread;search();list.querySelectorAll('.match').forEach(function(r){r.classList.remove('selected');});row.classList.add('selected');radio.checked=true;preview();}radio.addEventListener('change',choose);row.addEventListener('click',choose);row.addEventListener('dblclick',function(event){event.preventDefault();if(busy)return;choose();act('label');});radio.addEventListener('keydown',function(event){if(event.key==='Enter'){event.preventDefault();choose();act('label');}});list.appendChild(row);});preview();search();controls();}
 function load(result){if(result.unchanged)return;var previousHex=state&&state.groups[Number($('colors').value)].hex,previousCode=selected&&selected.code;state=result;var select=$('colors');select.textContent='';result.groups.forEach(function(g,i){var o=document.createElement('option');o.value=i;o.textContent=g.hex+' · '+g.count+' rellenos';select.appendChild(o);if(g.hex===previousHex)select.value=String(i);});render(previousCode);status(result.groups.length+' colores · '+(result.skipped?result.skipped+' omitidos':'selección sincronizada'));}
 function scan(){if(busy)return;request('ThreadMatchCEP.scan()',load);}
 function tick(){if(!alive)return;if(!busy&&$('auto').checked&&!document.hidden)request('ThreadMatchCEP.watch()',load);timer=setTimeout(tick,900);}
 function act(action){if(busy||!state||!selected)return;var code=selected.code;request('ThreadMatchCEP.act('+Number(state.token)+','+Number($('colors').value)+','+JSON.stringify(code)+','+JSON.stringify(action)+')',function(result){status(action==='apply'?'Hilo #'+code+' aplicado.':'Etiqueta #'+code+' creada.',false,true);if(action==='apply'){state=null;if(!manual)selected=null;scan();}});}
 function search(){var query=$('search-query').value.trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');var items=catalog.filter(function(t){return (t.code+' '+t.name).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').indexOf(query.replace(/^#/,''))!==-1;});var pages=Math.max(1,Math.ceil(items.length/5));page=Math.min(page,pages-1);var list=$('catalog-results');list.textContent='';items.slice(page*5,page*5+5).forEach(function(thread){var row=document.createElement('label');row.className='match'+(selected&&selected.code===thread.code?' selected':'');row.title=thread.code+' · '+name(thread.name);var radio=document.createElement('input');radio.type='radio';radio.name='catalog-thread';radio.value=thread.code;radio.checked=!!selected&&selected.code===thread.code;radio.disabled=busy;var chip=document.createElement('span');chip.className='chip';chip.style.backgroundColor=thread.hex;var text=document.createElement('div');text.className='thread-text';var title=document.createElement('b');title.textContent=thread.code+' · '+name(thread.name);text.appendChild(title);row.appendChild(radio);row.appendChild(chip);row.appendChild(text);function choose(){if(busy)return;manual=true;selected=thread;list.querySelectorAll('.match').forEach(function(r){r.classList.remove('selected');});row.classList.add('selected');radio.checked=true;document.querySelectorAll('#matches input').forEach(function(r){r.checked=r.value===thread.code;r.parentNode.classList.toggle('selected',r.checked);});preview();controls();}row.addEventListener('click',choose);radio.addEventListener('change',choose);row.addEventListener('dblclick',function(e){e.preventDefault();choose();act('label');});radio.addEventListener('keydown',function(e){if(e.key==='Enter'){e.preventDefault();choose();act('label');}});list.appendChild(row);});if(!items.length){var empty=document.createElement('div');empty.className='empty';empty.textContent='No hay hilos con ese código o nombre.';list.appendChild(empty);}$('search-count').textContent=items.length+' hilos · '+(page+1)+' / '+pages;$('previous-page').disabled=page===0;$('next-page').disabled=page===pages-1;}
 var sections=['threads','search-panel','label-settings'],tabs=['tab-threads','tab-search','tab-label'];
 function tab(which){sections.forEach(function(id,i){var active=which===i;$(id).hidden=!active;$(tabs[i]).setAttribute('aria-selected',String(active));$(tabs[i]).tabIndex=active?0:-1;});if(which===1)$('search-query').focus();}
 tabs.forEach(function(id,i){$(id).addEventListener('click',function(){tab(i);});$(id).addEventListener('keydown',function(e){if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();var next=(i+(e.key==='ArrowRight'?1:2))%3;tab(next);$(tabs[next]).focus();}});});
 $('search-query').addEventListener('input',function(){page=0;search();});$('previous-page').addEventListener('click',function(){page--;search();});$('next-page').addEventListener('click',function(){page++;search();});$('search-apply').addEventListener('click',function(){act('apply');});$('search-label').addEventListener('click',function(){act('label');});search();
 $('scan').addEventListener('click',scan);$('colors').addEventListener('change',function(){render();});$('auto').addEventListener('change',function(){if($('auto').checked)scan();});$('apply').addEventListener('click',function(){act('apply');});$('label').addEventListener('click',function(){act('label');});$('label-preview-create').addEventListener('click',function(){act('label');});window.addEventListener('beforeunload',function(){alive=false;clearTimeout(timer);});document.addEventListener('visibilitychange',function(){if(!document.hidden&&$('auto').checked)scan();});
 if(window.__adobe_cep__){scan();timer=setTimeout(tick,900);}else{clear('Instala y abre el panel desde Illustrator.');status('Ventana > Extensiones > ThreadMatch',false);}
}());
