(function(root){
 'use strict';var key='threadmatch.workspace.v1',favoriteKey='threadmatch.favorites.v1';
 function defaults(){return {schemaVersion:1,reference:'pdf',scope:'selection',title:'Diseño',client:'',recent:[],palettes:[],available:[],onlyAvailable:false,output:{widthMm:63.5,gapMm:6.35,fontPt:22,columns:2,placement:'below'},measured:null};}
 function clone(v){return JSON.parse(JSON.stringify(v));}
 function validate(input,catalog,engine){
  if(!input||input.schemaVersion!==1)throw Error('Versión de JSON incompatible.');var d=defaults(),known={};catalog.forEach(function(t){known[t.code]=true;});
  function codes(a){if(!Array.isArray(a)||a.length>160)throw Error('Lista de hilos inválida.');var seen={};return a.map(function(c){if(typeof c!=='string'||!known[c]||seen[c])throw Error('Código desconocido o duplicado: '+c);seen[c]=true;return c;});}
  function text(v,n){if(typeof v!=='string'||v.length>n)throw Error('Nombre inválido.');return v;}
  if(['pdf','montage','measured'].indexOf(input.reference)<0||['selection','artboard','document'].indexOf(input.scope)<0)throw Error('Referencia o alcance inválido.');
  d.reference=input.reference;d.scope=input.scope;d.title=text(input.title,100);d.client=text(input.client,100);d.available=codes(input.available);d.recent=codes(input.recent);if(d.recent.length>10)throw Error('Solo se admiten 10 hilos recientes.');if(typeof input.onlyAvailable!=='boolean')throw Error('Filtro inválido.');d.onlyAvailable=input.onlyAvailable;
  if(!Array.isArray(input.palettes)||input.palettes.length>100)throw Error('Paletas inválidas.');d.palettes=input.palettes.map(function(p){if(!p||['pdf','montage','measured'].indexOf(p.reference)<0||!Array.isArray(p.assignments)||p.assignments.length>10000)throw Error('Paleta inválida.');var seen={};return {name:text(p.name,100),client:text(p.client,100),reference:p.reference,assignments:p.assignments.map(function(a){if(!a||!/^#[0-9A-F]{6}$/.test(a.hex)||seen[a.hex]||!known[a.code]||typeof a.locked!=='boolean'||typeof a.exclude!=='boolean'||typeof a.reviewed!=='boolean')throw Error('Asignación inválida.');seen[a.hex]=true;return {hex:a.hex,code:a.code,locked:a.locked,exclude:a.exclude,reviewed:a.reviewed};})};});
  var o=input.output;if(!o)throw Error('Falta el formato de salida.');[['widthMm',35,140],['gapMm',1,30],['fontPt',8,36],['columns',1,4]].forEach(function(r){if(typeof o[r[0]]!=='number'||!isFinite(o[r[0]])||o[r[0]]<r[1]||o[r[0]]>r[2])throw Error('Medida inválida: '+r[0]);d.output[r[0]]=o[r[0]];});if(Math.floor(o.columns)!==o.columns||['below','artboard'].indexOf(o.placement)<0)throw Error('Posición o columnas inválidas.');d.output.placement=o.placement;
  if(input.measured){engine.measuredCatalog({colors:catalog},input.measured);d.measured=clone(input.measured);}if(d.reference==='measured'&&!d.measured)throw Error('Faltan los datos Lab medidos.');return d;
 }
 function create(storage,catalog,engine){var value=defaults();try{var raw=storage.getItem(key);if(raw)value=validate(JSON.parse(raw),catalog,engine);}catch(ignore){}
  function save(next){var valid=validate(next,catalog,engine),persisted=true;try{storage.setItem(key,JSON.stringify(valid));}catch(e){persisted=false;}value=valid;return persisted;}
  return {get:function(){return clone(value);},save:save,remember:function(code){var d=clone(value);d.recent=d.recent.filter(function(c){return c!==code;});d.recent.unshift(code);d.recent=d.recent.slice(0,10);return save(d);},exportData:function(favorites){return {kind:'ThreadMatch.workspace',schemaVersion:1,workspace:clone(value),favorites:favorites};},importData:function(data,replace){
   if(!data||data.kind!=='ThreadMatch.workspace'||data.schemaVersion!==1||!Array.isArray(data.favorites))throw Error('El archivo no es un respaldo de ThreadMatch.');var incoming=validate(data.workspace,catalog,engine),known={};catalog.forEach(function(t){known[t.code]=true;});var fav=data.favorites;if(fav.length>160||fav.some(function(c,i){return typeof c!=='string'||!known[c]||fav.indexOf(c)!==i;}))throw Error('Favoritos inválidos.');var next=incoming,oldFav=storage.getItem(favoriteKey),oldValue=storage.getItem(key);
   if(!replace){next=clone(value);next.palettes=next.palettes.concat(incoming.palettes.filter(function(p){return !next.palettes.some(function(q){return p.name===q.name&&p.client===q.client;});}));next.available=Array.from(new Set(next.available.concat(incoming.available)));next.recent=Array.from(new Set(incoming.recent.concat(next.recent))).slice(0,10);var parsed=oldFav?JSON.parse(oldFav):[];fav=Array.from(new Set(parsed.concat(fav)));if(incoming.measured&&!next.measured)next.measured=incoming.measured;}next=validate(next,catalog,engine);
   try{storage.setItem(key,JSON.stringify(next));storage.setItem(favoriteKey,JSON.stringify(fav));}catch(e){try{if(oldValue===null)storage.removeItem(key);else storage.setItem(key,oldValue);if(oldFav===null)storage.removeItem(favoriteKey);else storage.setItem(favoriteKey,oldFav);}catch(ignore){}throw Error('No se pudo guardar la importación. Se intentó restaurar el respaldo previo.');}value=next;return clone(value);
  }};
 }
 function xml(s){return String(s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c];});}
 function exportCSV(assignments,catalog,title,reference){var lookup={};catalog.forEach(function(t){lookup[t.code]=t;});function q(s){s=String(s);if(/^[=+@-]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}return '\uFEFF'+[['Trabajo','Referencia','Origen HEX','Código','Nombre','Hilo HEX','Fijado','Excluido','Revisado']].concat(assignments.map(function(a){var t=lookup[a.code];return [title,reference,a.hex,a.code,t?t.name:'',t?t.hex:'',a.locked,a.exclude,a.reviewed];})).map(function(r){return r.map(q).join(',');}).join('\r\n');}
 function exportSVG(assignments,catalog,title,reference,options){options=options||defaults().output;var lookup={},seen={},threads=[];catalog.forEach(function(t){lookup[t.code]=t;});assignments.forEach(function(a){if(!a.exclude&&!seen[a.code]&&lookup[a.code]){threads.push(lookup[a.code]);seen[a.code]=true;}});if(!threads.length)throw Error('No hay hilos incluidos.');var col=Math.min(options.columns,threads.length),cw=options.widthMm*72/25.4,w=col*cw,h=54+Math.ceil(threads.length/col)*45;return '<svg xmlns="http://www.w3.org/2000/svg" width="'+(w*25.4/72)+'mm" height="'+(h*25.4/72)+'mm" viewBox="0 0 '+w+' '+h+'"><rect width="100%" height="100%" fill="white"/><g font-family="Arial,sans-serif" fill="#141414"><text x="12" y="23" font-size="14">'+xml(title)+'</text><text x="12" y="40" font-size="8">Madeira Polystitch 40 · '+xml(reference)+'</text>'+threads.map(function(t,i){var x=i%col*cw+12,y=54+Math.floor(i/col)*45;return '<rect x="'+x+'" y="'+y+'" width="28" height="26" fill="'+xml(t.hex)+'" stroke="#969696" stroke-width="0.5"/><text x="'+(x+36)+'" y="'+(y+12)+'" font-size="'+Math.min(options.fontPt,14)+'">#'+xml(t.code)+'</text><text x="'+(x+36)+'" y="'+(y+26)+'" font-size="8" textLength="'+Math.min(t.name.length*4,cw-60)+'" lengthAdjust="spacingAndGlyphs">'+xml(t.name)+'</text>';}).join('')+'</g></svg>';}
 var api={key:key,defaults:defaults,validate:validate,create:create,exportCSV:exportCSV,exportSVG:exportSVG};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.ThreadMatchWorkspace=api;
}(this));
