var snapshot=null,sequence=0,documentSequence=0,lastDocument=null,recovery=null,operations={},operationOrder=[];
var reference='pdf',scope='selection',activeCatalog=ThreadMatch.catalog,rankCache=ThreadMatch.createRankCache(ThreadMatch.createMatcher(activeCatalog),128),configuration='';
function stringify(value){
 if(value===null)return 'null';
 if(typeof value==='string')return '"'+value.replace(/\\/g,'\\\\').replace(/"/g,'\\"').replace(/[\x00-\x1f\u2028\u2029]/g,function(c){return '\\u'+('0000'+c.charCodeAt(0).toString(16)).slice(-4);})+'"';
 if(typeof value==='number')return isFinite(value)?String(value):'null';
 if(typeof value==='boolean')return value?'true':'false';
 var parts=[],i,key;if(value instanceof Array){for(i=0;i<value.length;i++)parts.push(stringify(value[i]));return '['+parts.join(',')+']';}
 for(key in value)if(value.hasOwnProperty(key))parts.push(stringify(key)+':'+stringify(value[key]));return '{'+parts.join(',')+'}';
}
function failure(e){return stringify({ok:false,error:e.message||'No se pudo completar la operación.',recoverable:!!recovery});}
function configure(mode,options){options=options||{};mode=mode||'pdf';var key=stringify({reference:mode,scope:options.scope||'selection',available:options.available||null,measured:options.measured||null});if(key!==configuration){activeCatalog=mode==='measured'?ThreadMatch.measuredCatalog(ThreadMatch.catalog,options.measured):ThreadMatch.catalogForReference(ThreadMatch.catalog,mode);reference=mode;scope=options.scope||'selection';if(scope!=='selection'&&scope!=='document'&&scope!=='artboard')throw Error('Alcance inválido.');configuration=key;rankCache=ThreadMatch.createRankCache(ThreadMatch.createMatcher(activeCatalog),128);snapshot=null;}return options;}
function threadByCode(code){for(var i=0;i<activeCatalog.colors.length;i++)if(activeCatalog.colors[i].code===code)return activeCatalog.colors[i];throw Error('Código de hilo desconocido.');}
function sameAnalysis(analysis){if(!snapshot||analysis.groups.length!==snapshot.analysis.groups.length||analysis.skipped!==snapshot.analysis.skipped||analysis.roots.length!==snapshot.analysis.roots.length)return false;for(var r=0;r<analysis.roots.length;r++)if(analysis.roots[r]!==snapshot.analysis.roots[r])return false;for(var i=0;i<analysis.groups.length;i++){var a=analysis.groups[i],b=snapshot.analysis.groups[i];if(a.hex!==b.hex||a.targets.length!==b.targets.length)return false;for(var j=0;j<a.targets.length;j++)if(a.targets[j].item!==b.targets[j].item||a.targets[j].fingerprint!==b.targets[j].fingerprint)return false;}return true;}
function validateSnapshot(token){if(recovery&&recovery.incomplete)throw Error('Completa la recuperación pendiente antes de escribir.');if(!snapshot||token!==snapshot.token)throw Error('Actualiza el análisis antes de continuar.');if(!app.documents.length||app.activeDocument!==snapshot.doc)throw Error('Cambió el documento. Espera a la sincronización o pulsa Actualizar.');var current;try{current=ThreadMatch.collectScope(snapshot.doc,scope);}catch(e){throw Error('Cambió la selección o un relleno del diseño: '+e.message);}if(!sameAnalysis(current))throw Error('Cambió la selección o un relleno del diseño. Espera a la sincronización o pulsa Actualizar.');if(stringify(ThreadMatch.documentContext(snapshot.doc))!==snapshot.contextKey)throw Error('Cambió el contexto de color del documento.');if(scope==='artboard'&&snapshot.board!==snapshot.doc.artboards.getActiveArtboardIndex())throw Error('Cambió la mesa activa.');}
function legends(doc){var result=[],items=doc.groupItems||[];for(var i=0;i<items.length;i++){try{var m=/^ThreadMatch\.legend\.v1\|(.+)$/.exec(items[i].note||'');if(m&&!items[i].hidden)result.push({id:m[1],name:items[i].name});}catch(ignore){}}return result;}
function contains(list,value){for(var i=0;i<list.length;i++)if(list[i]===value)return true;return false;}
function readScope(onlyChanged,mode,options){try{var started=new Date().getTime();options=configure(mode,options);if(!app.documents.length){snapshot=null;throw Error('Abre un documento de Illustrator.');}var doc=app.activeDocument,analysis=ThreadMatch.collectScope(doc,scope),groups=[],i,j,ranked,matches,rankStart=new Date().getTime(),context=ThreadMatch.documentContext(doc),contextKey=stringify(context),board=scope==='artboard'?doc.artboards.getActiveArtboardIndex():null;
 if(lastDocument!==doc){lastDocument=doc;documentSequence++;}
 if(onlyChanged&&snapshot&&snapshot.doc===doc&&snapshot.contextKey===contextKey&&snapshot.board===board&&sameAnalysis(analysis))return stringify({ok:true,unchanged:true,metrics:{readMs:analysis.readMs,totalMs:new Date().getTime()-started,cache:rankCache.stats()},recoverable:!!recovery});
 for(i=0;i<analysis.groups.length;i++){ranked=rankCache.rank(analysis.groups[i].rgb);matches=[];for(j=0;j<ranked.length&&matches.length<5;j++){if(options.available&&!contains(options.available,ranked[j].code))continue;matches.push({code:ranked[j].code,name:ranked[j].name,hex:ranked[j].thread.hex,deltaE:ranked[j].deltaE,description:ThreadMatch.matchDescription(ranked[j].deltaE)});}groups.push({hex:analysis.groups[i].hex,rgb:analysis.groups[i].rgb,count:analysis.groups[i].targets.length,matches:matches});}
 snapshot={doc:doc,analysis:analysis,token:++sequence,contextKey:contextKey,board:board};return stringify({ok:true,token:sequence,documentId:documentSequence,groups:groups,skipped:analysis.skipped,reasons:analysis.reasons,context:context,reference:reference,scope:scope,legends:legends(doc),recoverable:!!recovery,metrics:{readMs:analysis.readMs,rankMs:new Date().getTime()-rankStart,totalMs:new Date().getTime()-started,visited:analysis.visited,cache:rankCache.stats()}});
}catch(e){snapshot=null;return failure(e);}}
function entriesFor(assignments){if(!(assignments instanceof Array)||assignments.length!==snapshot.analysis.groups.length)throw Error('La tabla no contiene todos los colores del diseño.');var entries=[],seen={},i,j,a,bucket;for(i=0;i<assignments.length;i++){a=assignments[i];if(!a||typeof a.exclude!=='boolean'||typeof a.locked!=='boolean'||typeof a.reviewed!=='boolean')throw Error('Estado de asignación inválido.');if(seen[a.hex])throw Error('Hay colores duplicados en la tabla.');seen[a.hex]=true;bucket=null;for(j=0;j<snapshot.analysis.groups.length;j++)if(snapshot.analysis.groups[j].hex===a.hex)bucket=snapshot.analysis.groups[j];if(!bucket)throw Error('Color de origen desconocido.');if(a.exclude)continue;if(a.reviewed!==true)throw Error('Revisa o excluye cada color antes de continuar.');entries.push({bucket:bucket,thread:threadByCode(a.code)});}if(!entries.length)throw Error('No hay colores incluidos.');return entries;}
function mergeLabelOptions(options){options=options||{};var next={},k;for(k in options)if(options.hasOwnProperty(k))next[k]=options[k];next.reference=reference;return next;}
function runTransaction(entries,action,options){if(action!=='apply'&&action!=='legend'&&action!=='both')throw Error('Acción inválida.');options=options||{};var doc=snapshot.doc,unique=[],seen={},buckets=[],previous=null,i;
 if(options.replaceLegendId){var items=doc.groupItems||[];for(i=0;i<items.length;i++)if(items[i].note==='ThreadMatch.legend.v1|'+options.replaceLegendId)previous=items[i];if(!previous||previous.locked||previous.hidden||previous.editable===false)throw Error('La leyenda a actualizar no está disponible.');}
 var tx=ThreadMatch.beginTransaction(doc,action==='legend'?[]:entries);
 try{if(action!=='legend')tx.apply();if(action!=='apply'){for(i=0;i<entries.length;i++){buckets.push(entries[i].bucket);if(!seen[entries[i].thread.code]){unique.push(entries[i].thread);seen[entries[i].thread.code]=true;}}tx.group=ThreadMatch.createLegend(doc,buckets,unique,options,'op-'+new Date().getTime()+'-'+sequence,reference);tx.groupSignature=ThreadMatch.outputSignature(tx.group);if(previous){tx.previousGroup=previous;tx.previousHidden=previous.hidden;previous.hidden=true;}}recovery=tx;snapshot=null;app.redraw();return {ok:true,action:action,colors:entries.length,recoverable:true};}catch(e){var failures=tx.rollback();if(failures){tx.incomplete=true;recovery=tx;e=Error((e.message||'Falló la operación.')+' Recuperación parcial: '+failures+' pasos pendientes. Usa Recuperar.');}throw e;}}
function remembered(id,payload,perform){if(typeof id!=='string'||!/^[a-zA-Z0-9-]{8,100}$/.test(id))throw Error('Identificador de operación inválido.');if(operations[id]){if(operations[id].payload!==payload)throw Error('El identificador ya pertenece a otra operación.');return operations[id].result;}var result=perform();operations[id]={payload:payload,result:result};operationOrder.push(id);if(operationOrder.length>100)delete operations[operationOrder.shift()];return result;}
return {
 scan:function(mode,options){return readScope(false,mode,options);},watch:function(mode,options){return readScope(true,mode,options);},
 act:function(token,index,code,action,options){try{validateSnapshot(token);if(action!=='apply'&&action!=='label')throw Error('Acción inválida.');if(typeof index!=='number'||index<0||Math.floor(index)!==index||index>=snapshot.analysis.groups.length)throw Error('Color inválido.');var bucket=snapshot.analysis.groups[index],thread=threadByCode(code);if(action==='apply')return stringify(runTransaction([{bucket:bucket,thread:thread}],'apply',options));ThreadMatch.createThreadLabel(snapshot.doc,{targets:bucket.targets,hex:bucket.hex,rgb:bucket.rgb,allBuckets:snapshot.analysis.groups},thread,mergeLabelOptions(options));app.redraw();return stringify({ok:true,code:code,action:action});}catch(e){return failure(e);}},
 batch:function(token,assignments,action,options,id){try{return remembered(id,stringify({token:token,assignments:assignments,action:action,options:options||{}}),function(){validateSnapshot(token);return stringify(runTransaction(entriesFor(assignments),action,options));});}catch(e){return failure(e);}},
 reduce:function(token,assignments,limit,available){try{validateSnapshot(token);if(assignments.length!==snapshot.analysis.groups.length)throw Error('Tabla incompleta.');for(var i=0;i<assignments.length;i++)if(assignments[i].hex!==snapshot.analysis.groups[i].hex)throw Error('Cambió el orden de colores.');var allowed=null;if(available){allowed={};for(i=0;i<available.length;i++)allowed[available[i]]=true;}return stringify({ok:true,assignments:ThreadMatch.reducePalette(snapshot.analysis.groups,assignments,activeCatalog,limit,allowed)});}catch(e){return failure(e);}},
 recover:function(){try{if(!recovery)throw Error('No hay operación para recuperar.');if(!app.documents.length||app.activeDocument!==recovery.doc)throw Error('Activa el documento de la operación.');recovery.validateRecovery();var pending=recovery.rollback();if(pending)throw Error('Quedan '+pending+' pasos por recuperar.');var kept=recovery.keptSwatches||0;recovery=null;snapshot=null;app.redraw();return stringify({ok:true,recoverable:false,keptSwatches:kept});}catch(e){return failure(e);}},
 health:function(){return stringify({ok:true,recoverable:!!recovery,documents:app.documents.length,operations:operationOrder.length});},
 saveFile:function(kind,content){var file=null;try{if(kind!=='csv'&&kind!=='json'&&kind!=='svg')throw Error('Formato inválido.');if(typeof content!=='string'||content.length>2000000)throw Error('Contenido inválido.');file=File.saveDialog('Guardar ThreadMatch · '+kind.toUpperCase());if(!file)return stringify({ok:true,cancelled:true});if(!new RegExp('\\.'+kind+'$','i').test(file.name))file=new File(file.fsName+'.'+kind);file.encoding='UTF-8';if(!file.open('w'))throw Error('No se pudo abrir el archivo para escritura.');var written=file.write(content);file.close();if(written===false)throw Error('No se pudo escribir el archivo completo.');return stringify({ok:true});}catch(e){if(file)try{file.close();}catch(ignore){}return failure(e);}},
 openFile:function(){var file=null;try{file=File.openDialog('Importar JSON de ThreadMatch');if(!file)return stringify({ok:true,cancelled:true});if(file.length>2000000)throw Error('El JSON supera 2 MB.');file.encoding='UTF-8';if(!file.open('r'))throw Error('No se pudo leer el archivo.');var content=file.read();file.close();return stringify({ok:true,content:content});}catch(e){if(file)try{file.close();}catch(ignore){}return failure(e);}}
};
